### ISSUE TITLE
Does not run in Python3

### ISSUE THREAD

**Issue by nvictor** [xflr6/graphviz#10]
I may be missing something but it seems that this package hasn't been tested with Python 3. The module that it's failing on for me is "graphviz/lang.py"

**Comment by xflr6** [comment]
Thanks for reporting: Can you provide a short code example that fails and/or the traceback produced?

**Comment by nvictor** [comment]
it's all my fault actually. i was debugging the code and found that quote() and quote_edge() expect identifier to be a string or buffer. nevermind this one : )
