### ISSUE TITLE
Issue rendering graph

### ISSUE THREAD

**Issue by rajvijay68** [xflr6/graphviz#103]
When I am working with a subset of my data, it works.

But when I use the whole dataset, it gives this error : 

`CalledProcessError: Command '['dot.bat', '-Tpdf', '-O', 'ip_graph1.gv']' returned non-zero exit status 3221225725. [stderr: b'']
`

**Comment by xflr6** [comment]
I would speculate the exit status hints at too much memory used.
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by xflr6** [comment]
Closing for now (feel free to re-open if you can make this reproducible).

This looks more like an issue with the underlying [Graphviz](https://www.graphviz.org) drawing software (not with the Python interface provided by this library), so maybe consider [reporting upstream](https://gitlab.com/graphviz/graphviz/-/issues).

**Comment by rajvijay68** [comment]
@xflr6, yes, this was a memory issue. I was trying to visualize data of size around 200 MB. I had to prune the nodes to be able to do it.

**Comment by xflr6** [comment]
Thanks for the confirmation.
