### ISSUE TITLE
The text goes out of box after using font 'IBM Plex Sans'

### ISSUE THREAD

**Issue by ilovepumpkin** [xflr6/graphviz#104]
Here is out part of DOT string 
`
"digraph Tree {\nnode [shape=box, style=\"rounded\", color=\"black\", fontname=helvetica] ;\nedge [fontname=helvetica] ;\n0 [label=\"ob_2 <= 0.5\\nentropy = 2.002\\nsamples = 100.0%\\nvalue = [0.667, 0.021, 0.042, 0.042, 0.021, 0.021, 0.021, 0.021\\n0.021, 0.021, 0.021, 0.083]\"] ;\n1 [label=\"ob_3 <= 0.5\\nentropy = 3.093\\nsamples = 29.2%\\nvalue = [0.0, 0.071, 0.143, 0.0, 0.071, 0.071, 0.071, 0.071\\n0.071, 0.071, 0.071, 0.286]\"] ;`

When fontname is 'helvetical', it is rendered well. 
![image](https://user-images.githubusercontent.com/11310645/89848790-9d237200-dbb9-11ea-88bd-26b0dc1fa975.png)

But after I changed the fontname to "IBM Plex Sans", the text goes out of the box. 

"digraph Tree {\nnode [shape=box, style=\"rounded\", color=\"black\", fontname=\"IBM Plex Sans\"] ;\nedge [fontname=\"IBM Plex Sans\"] ;\n0 [label=\"ob_2 <= 0.5\\nentropy = 2.002\\nsamples = 100.0%\\nvalue = [0.667, 0.021, 0.042, 0.042, 0.021, 0.021, 0.021, 0.021\\n0.021, 0.021, 0.021, 0.083]\"] ;\n1 [label=\"ob_3 <= 0.5\\nentropy = 3.093\\nsamples = 29.2%\\nvalue = [0.0, 0.071, 0.143, 0.0, 0.071, 0.071, 0.071, 0.071\\n0.071, 0.071, 0.071, 0.286]\"] ;`
![image](https://user-images.githubusercontent.com/11310645/89848873-d5c34b80-dbb9-11ea-8ce0-6cf0e15e3b2b.png)

What am I supposed do to fix this issue?

**Comment by xflr6** [comment]
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

IIUC, you are manually breaking the node label(s) into multiple lines. So if the other font is wider, you might neeed to adapt the manual line breaks (see also [documentation on backslash escapes](https://graphviz.readthedocs.io/en/stable/manual.html#backslash-escapes)), e.g.:

```python
import graphviz

d = graphviz.Digraph(node_attr={'shape': 'box',
                                'style': 'rounded',
                                'color': 'black',
                                'fontname': 'helvetica'},
                     edge_attr={'fontname': 'helvetica'})

d.node('0', label=r'ob_2 <= 0.5\n'
                  r'entropy = 2.002\n'
                  r'samples = 100.0%\n'
                  r'value = [0.667, 0.021, 0.042, 0.042, 0.021,\n'
                  r'0.021, 0.021, 0.021, 0.021, 0.021, 0.021, 0.083]')

d
```
![output](https://user-images.githubusercontent.com/6342379/89874167-c5ac6b80-dbbb-11ea-9c9f-0d7a622bce21.png)

**Comment by ilovepumpkin** [comment]
@xflr6 sorry that I did not provide reproducible example. 

I did a test by removing all "\n" from node label add some Chinese characters, the text seems still possible to go out of the box. That means manual line breaks may not solve all the cases, correct? Is there any better way? 

![image](https://user-images.githubusercontent.com/11310645/89968207-d45f5500-dc85-11ea-9729-30f58616d097.png)

**Comment by ilovepumpkin** [comment]
@xflr6 I created a reproducible demo here [https://codepen.io/ilovepumpkin/pen/ExKVeYO](https://codepen.io/ilovepumpkin/pen/ExKVeYO) . If without adding line breaks manually, is there any way to wrap the long text intelligently for different font width?

**Comment by xflr6** [comment]
Thanks. From the [Graphviz docs](https://www.graphviz.org/doc/info/attrs.html#k:escString) and SO-questions like [this](https://stackoverflow.com/questions/5277864/text-wrapping-with-dot-graphviz), I don't  think Graphviz supports text wrapping of labels (though there seem to be a workaround combining it with LaTeX, see second link).

Note that this is a limitation in the underlying [Graphviz](https://www.graphviz.org) drawing software (not with the Python interface provided by this library), so if you want to file a feature request please consider taking it [upstream](https://gitlab.com/graphviz/graphviz/-/issues).  Closing.

**Comment by ilovepumpkin** [comment]
@xflr6 okay, I got it. Thank you for your reply!
