### ISSUE TITLE
Error occurred while rendering graph

### ISSUE THREAD

**Issue by shengqiangzhang** [xflr6/graphviz#105]
## Enviroment
- os version: MacOSX
- graphviz version: 0.14

## Error

When node name is '\\' or node name includes '\\', it will prompt some error:
```bash
Error: test.gv: syntax error in line 3 scanning a quoted string (missing endquote? longer than 16384?)
String starting:""]
        2 [label=test]
        1 -> 2
}

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bird/anaconda3/envs/python36/lib/python3.6/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/Users/bird/anaconda3/envs/python36/lib/python3.6/site-packages/graphviz/backend.py", line 223, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/Users/bird/anaconda3/envs/python36/lib/python3.6/site-packages/graphviz/backend.py", line 186, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tpdf', '-O', 'test.gv']' returned non-zero exit status 1. [stderr: b'Error: test.gv: syntax error in line 3 scanning a quoted string (missing endquote? longer than 16384?)\nString starting:""]\n\t2 [label=test]\n\t1 -> 2\n}\n\n']
```

 
## Reproduce
```python
from graphviz import Digraph
dot = Digraph(comment='Abstract Syntax Tree')
dot.node("1", "\\")
dot.node("2", "test")
dot.edge("1", "2")
dot.render("test.gv", view=False)

```

Has anyone finded this problem before? 
Many thanks!

**Comment by shengqiangzhang** [comment]
"<[^<]+?>" will also cause an error
I do need to set the node name to "\" or "<[^<]+?>"

**Comment by xflr6** [comment]
Hi. Please see the [documentation on backslash escapes](https://graphviz.readthedocs.io/en/stable/manual.html#backslash-escapes): Similar to the  stdlib `re` module, you need to escape (double) a backslash to render a **literal** backslash, e.g. (assuming it is intended to render a single literal backslash here):

```python
from graphviz import Digraph

dot = Digraph(comment='Abstract Syntax Tree')
dot.node("1", r"\\")
dot.node("2", "test")
dot.edge("1", "2")
dot
```
![spam](https://user-images.githubusercontent.com/6342379/92321289-010a5080-f029-11ea-99cf-6d5766cf5587.png)

There is also a [notebook giving some interesting examples for escapes/quoting](https://nbviewer.jupyter.org/github/xflr6/graphviz/blob/master/examples/graphviz-escapes.ipynb) in the examples.

> "<[^<]+?>" will also cause an error
> I do need to set the node name to "" or "<[^<]+?>"

Should the intended result include literal double quotes?

```python
from graphviz import Digraph

dot = Digraph()
dot.node("1", '"<[^<]+?>"')
dot.node("2", '""')
dot.edge("1", "2")
dot
```
![spam2](https://user-images.githubusercontent.com/6342379/92321356-8ee63b80-f029-11ea-8fd8-54f238605382.png)

If **not**, please see the [documentation on quoting and HTML-like labels](https://graphviz.readthedocs.io/en/stable/manual.html#quoting-and-html-like-labels), e.g.:

```python
from graphviz import Digraph, escape

dot = Digraph()
dot.node("1", escape('<[^<]+?>'))
dot.node("2", '')
dot.edge("1", "2")
dot
```
![spam3](https://user-images.githubusercontent.com/6342379/92321519-036daa00-f02b-11ea-91e1-2c6d3589fc8d.png)

If  you want to render all characters literally (i.e. use neither backslash nor HTML-like escapes), consider using the [graphviz.escape function](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.escape) (see [graphviz.nohtml](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.nohtml) to disable the latter only).

**Comment by shengqiangzhang** [comment]
@xflr6 Thanks for your help! I have solved the problem.
