### ISSUE TITLE
No API to close view?

### ISSUE THREAD

**Issue by WhyNotPal** [xflr6/graphviz#106]
Hi, 
Forgive me if I missed it, but it there a way to close a eog window opened by the view() API? 
As it happens, my program needs at least 2 such views, that must be updated. 
If view() is called on an already opened filename, that sometimes causes EOG errors.
Closing a single view via a system call does not seem possible since '_ps aux_' will only attribute a single PID for the 2 views: closing one view via _'kill -9 PID_' will hence close both views. 

any idea?? 
Thanks a lot
Paloma

**Comment by xflr6** [comment]
Hi, good question. The [implementation of `view()`](https://github.com/xflr6/graphviz/blob/21bf42ac043433c157334d9f18057b5c1f739d3c/graphviz/backend.py#L287-L312) is platform-specific. Under Windows, we are currently using [`os.startfile()`](https://docs.python.org/3/library/os.html#os.startfile) which does not provide a return value that would be needed here:

> startfile() returns as soon as the associated application is launched.
> There is no option to wait for the application to close, and no way to retrieve the application’s exit status

On the other two platforms, we might return the `subprocess.Popen` instance. Can you verify that that provides the instance with the right pid for the viewer process? E.g. the following starting the viewer directly does indeed allow to control it (testing on Windows here):

```python
import subprocess

READER = 'C:\\Program Files (x86)\\Adobe\Acrobat Reader DC\\Reader\AcroRd32.exe'

FILE = 'C:\\Users\\User\\Desktop\\spam.pdf'

p = subprocess.Popen([READER, FILE])

p.terminate()   # or p.communicate() to block until the viewer is closed
```

However,  but I am not sure if the same holds using the generic methods e.g. `xdg-open` under Linux.

> If view() is called on an already opened filename, that sometimes causes EOG errors.
> 'ps aux' will only attribute a single PID for the 2 views

That might be specific to the registered viewing application on your system ([Eye of GNOME](https://help.gnome.org/users/eog/stable/)) and/or the details of what `xdg-open` (or `open`on a Mac) does.

**Comment by xflr6** [comment]
Okay, tried `p = subprocess.Popen(['xdg-open', FILE])` on Linux: `p.pid` is the pid of the xdg-open process and killing it does not seem to affect viewing (think of a running browser taken into foreground as pdf viewer).

I think about adding a note to the docs for `view()` with a variation of the `os.startfile()` doc note cited above.

**Comment by xflr6** [comment]
Added to the documentation and closed. Feel free to re-open in case you think I have missed something.

**Comment by WhyNotPal** [comment]
Hey Sebastian, 
thanks for your reply - sorry I didn't look it up earlier, i was busy elsewhere. :-) 
I'll explore the tracks you mention - thanks for the pointers. 
(view_unixoid -> good one!!)

**Comment by WhyNotPal** [comment]
Hey, Sebastian, again. 
After a quick test, I wonder if the p = subprocess.Popen(['xdg-open', FILE]).pid is not the PID of the encaspulating subprocess itself? 
In any case, a solution is probably to keep track of the PIDs each time a view() is called via 
os.system("ps aux | grep eog |head -n1 | awk '{print $2}' ")

Interesting to note -> the PID does not appear immediately in the ps aux list, a waiting time of 1 sec is required first. 

Anyway, thanks for your help, learned something new today! :-)

**Comment by xflr6** [comment]
Thanks. Yes, I came to the same conclusion above: the PID we get  is the one of `xdg-open`. Which viewer process is started in the depends on your configuration for the file type and AFAIU there is also no guarantee that a new process is started in the first place (an already open viewer might just be taken into the foreground).

> os.system("ps aux | grep eog |head -n1 | awk '{print $2}' ")

This is why I don't think this kind of functionality is a candidate for this library (would require too much guessing and probably relatively heavy dependencies such as [psutil](https://pypi.org/project/psutil) to implement this for all plarforms).

However, you can probably still implement the viewer-handling you need for your environment in your own code (e.g. subclassing  `Graph` and ' Digraph` overriding their `view()`-methods).

**Comment by WhyNotPal** [comment]
(Sorry :-)
Anyway, overwriting works, just had to replace 
cmd = ['xdg-open', filepath]
with 
cmd = ['eog','-n' ,filepath]
the -n option forces to open a new window each time. 
Thanks a lot, anyway!! Have a nice day!
