### ISSUE TITLE
Format: "pdf" not recognized. Use one of:

### ISSUE THREAD

**Issue by ImanoWilliams** [xflr6/graphviz#108]
I got: 
graphviz.backend.CalledProcessError: Command '['dot', '-Tpdf', '-O', 'hello.gv']' returned non-zero exit status 1. [stderr: b'Format: "pdf" not recognized. Use one of:\r\n']

when I ran:

from graphviz import Digraph

g = Digraph('G', filename='hello.gv')

g.edge('Hello', 'World')

g.view()

**Comment by xflr6** [comment]
Hi, this comes from the rendering `dot` process.

I suspect that there is a problem with your installation of Graphviz (or  how it was build), not this Python package. Can you provide more details whatyou have installed?

This might be something for [upstream](https://gitlab.com/graphviz/graphviz/-/issues?scope=all&utf8=%E2%9C%93&state=all&search=%22not+recognized%22) (maybe  try `dot -c`?).

**Comment by ImanoWilliams** [comment]
Hi,

1. I went to [](https://graphviz.org/download/), then I [](https://www2.graphviz.org/Packages/stable/windows/10/), next, I downloaded [](https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/).
2. I then install install graphviz-install-2.44.1-win64.exe. 
3. Then Environment variables -> System Variables --> to set the path to graphviz.
4. Restart computer
5. I install Graphviz using **pip install graphviz**
6. Open PyCharm

**Comment by ImanoWilliams** [comment]
@xflr6 I followed https://stackoverflow.com/a/62549025/9865882 and it seems work work right now.

**Comment by xflr6** [comment]
Great, `dot -c` was something I  also saw in one of the upstream bugs, thanks, closing  (maybe this is worth an upstream bug to document this in the installer?).

**Comment by xflr6** [comment]
See also [new-simplified-installation-procedure-on-windows](https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224#format-svg-not-recognized-use-one-of).
