### ISSUE TITLE
Unable to install pygraphviz

### ISSUE THREAD

**Issue by SC4V** [xflr6/graphviz#109]
PS C:\Users\91975\Desktop\pygraphviz-1.6> python setup.py install
  File "setup.py", line 2
    C:\Program Files (x86)\Graphviz 2.44.1\include\graphviz
                                                                                           ^
SyntaxError: unexpected character after line continuation character

I am getting the above error while installing pygraphviz

**Comment by xflr6** [comment]
Hi there. This seems to be about [pygraphviz](https://github.com/pygraphviz/pygraphviz) not [this library](https://pypi.org/project/graphviz/), closing.

**Comment by egberts** [comment]
Yeah,   I got confused too.   Had to check the actual distro package for its URL and made sure that one went to the correct repository/issue/bugzilla site.

**Comment by xflr6** [comment]
Thanks. There are [different libraries to use Graphviz from Python](https://github.com/xflr6/graphviz#see-also). You can find the bug tracker for `pygraphviz` here https://github.com/pygraphviz/pygraphviz/issues
