### ISSUE TITLE
CalledProcessError in graphviz 2.44.1 with `pipe` method

### ISSUE THREAD

**Issue by yoelcortes** [xflr6/graphviz#115]
The `pipe` method works for graphviz 2.38, but not with graphviz 2.44.1 on Windows 10. I'm using graphviz v0.14.2 on PyPI.

To reproduce the error:
```python
>>> from graphviz import Digraph
>>> f = Digraph()
>>> f.pipe(format='png')
Traceback (most recent call last):
CalledProcessError: Command '['dot', '-Tpng']' returned non-zero exit status 1. [stderr: b'Format: "png" not recognized. Use one of:\r\n']
```
The following example from the stable documentation also raises an error:
```python
>>> h = Graph('hello', format='svg')
>>> h.edge('Hello', 'World')
>>> print(h.pipe().decode('utf-8')) 
Traceback (most recent call last):
CalledProcessError: Command '['dot', '-Tsvg']' returned non-zero exit status 1. [stderr: b'Format: "svg" not recognized. Use one of:\r\n']
```
I implement graphviz in python to generate diagrams of industrial process models in BioSTEAM: https://biosteam.readthedocs.io/en/latest/tutorial/Getting_started.html
Graphviz has been super convenient for this task.

Thanks in advanced for your help!

**Comment by xflr6** [comment]
Thanks. This looks similar to #108 (solution was to run `dot -c` as Administrator, see [SO question](https://stackoverflow.com/questions/35688320/graphviz-seems-doesnt-support-png-and-map/62549025#62549025)).

Can you maybe report this [upstream](https://gitlab.com/graphviz/graphviz/-/issues) (IIUC this might be an issue with the Windows build or installation procedure)?

**Comment by yoelcortes** [comment]
Thanks, it worked! I'll close the issue

**Comment by xflr6** [comment]
See also [new-simplified-installation-procedure-on-windows](https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224#format-svg-not-recognized-use-one-of).
