### ISSUE TITLE
`run` method hides function `input` (code smell)

### ISSUE THREAD

**Issue by C0DK** [xflr6/graphviz#117]
I was looking at your code and saw that you use `input` as the arg for an input string in the `run` method, on your backend. May i suggest to change it to something else. If yes, I would gladly submit a PR (Especially if you mark it as hacktoberfest friendly :P)

**Comment by xflr6** [comment]
Hi Casper.

https://github.com/xflr6/graphviz/blob/0c503a32f5f17f99a6e0ad8ac29fb441e3c0a9f2/graphviz/backend.py#L150-L152

This is an internal function (see [API docs](https://graphviz.readthedocs.io/en/stable/api.html)). I would not call this a code smell. I understand that this is something a linter might flag (depending on the configuration). As to where one should avoid to shadow access of e.g. builtins, there are pros and cons. This function follows the stdlib `subprocess.run()`(https://docs.python.org/3/library/subprocess.html#subprocess.run).
