### ISSUE TITLE
Doesn't find a dependency in things define in global scope. 

### ISSUE THREAD

**Issue by C0DK** [xflr6/graphviz#119]
Should probably be a dependency of the file/module then.

**Comment by xflr6** [comment]
Hi Casper. I am not sure what this is about (e.g. what you mean by 'dependency' or 'things in global scope'.

Can you provide a pointer to the relevant code, a code example, an error message or something similar?

**Comment by C0DK** [comment]
ups i created this in the wrong project. I am every sorry about this haha. Was meant to be a note to my self. Sorry!!
