### ISSUE TITLE
Support for HTML labels?

### ISSUE THREAD

**Issue by jyuhuan** [xflr6/graphviz#12]
How do I create the following graph using your library (this is from [the official website of GraphViz](http://www.graphviz.org/doc/info/html3.gv)): 

	digraph structs {
	    node [shape=plaintext];

	    struct1 [label=<<TABLE>
		<TR>
		    <TD>line 1</TD>
		    <TD BGCOLOR="blue"><FONT COLOR="white">line2</FONT></TD>
		    <TD BGCOLOR="gray"><FONT POINT-SIZE="24.0">line3</FONT></TD>
		    <TD BGCOLOR="yellow"><FONT POINT-SIZE="24.0" FACE="ambrosia">line4</FONT></TD>
		    <TD>
		      <TABLE CELLPADDING="0" BORDER="0" CELLSPACING="0">
	          <TR>
	            <TD><FONT COLOR="green">Mixed</FONT></TD>
	            <TD><FONT COLOR="red">fonts</FONT></TD>
	          </TR>
		      </TABLE>
	        </TD>
		</TR>
	    </TABLE>>];
	}

**Comment by xflr6** [comment]
It translates pretty much directly (support for HTML-labels was added in #6):
```python
from graphviz import Digraph

g = Digraph('structs', node_attr={'shape': 'plaintext'})

g.node('struct1', label='''<
<TABLE>
  <TR>
    <TD>line 1</TD>
    <TD BGCOLOR="blue"><FONT COLOR="white">line2</FONT></TD>
    <TD BGCOLOR="gray"><FONT POINT-SIZE="24.0">line3</FONT></TD>
    <TD BGCOLOR="yellow"><FONT POINT-SIZE="24.0" FACE="ambrosia">line4</FONT></TD>
    <TD>
      <TABLE CELLPADDING="0" BORDER="0" CELLSPACING="0">
        <TR>
          <TD><FONT COLOR="green">Mixed</FONT></TD>
          <TD><FONT COLOR="red">fonts</FONT></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
</TABLE>>''')

g.view()
```
Another more complex exampe from the Graphviz docs is in `tests/test_dot.py`.
