### ISSUE TITLE
Version 0.16 Windows dot.bat used as argument in cmd "dot -Kdot.bat" rather than correct "dot.bat -Kdot" 

### ISSUE THREAD

**Issue by carlrose** [xflr6/graphviz#124]
This change occurred in going from version 0.15 to version in backup.py around line 124. The command should always be 
dot or dot.bat for windows with the -K argument specifying the layout engine.

**Comment by xflr6** [comment]
You seem to be using the (downstream) conda-forge [python-graphviz](https://anaconda.org/conda-forge/python-graphviz) package: [python-graphviz-feedstock](https://github.com/conda-forge/python-graphviz-feedstock).

Note that `dot.bat` is something that is only found in that package.

See conda-forge/python-graphviz-feedstock#42, closing (downstream issue).
