### ISSUE TITLE
Migrate to pathlib?

### ISSUE THREAD

**Issue by eumiro** [xflr6/graphviz#125]
How about introducing `pathlib.Path` to all directory/file operations? This would make clear which objects represent which disk entities and replace the `os.path` hacks with proper object attributes.

In the tests `tmpdir` fixtures are used. On https://py.readthedocs.io/en/latest/path.html there's *“Note: The ‘py’ library is in “maintenance mode” and so is not recommended for new projects. Please check out pathlib or pathlib2 for path operations.”* and the PyTest is also [migrating to Python's stdlib `pathlib`](https://github.com/pytest-dev/pytest/search?q=py.path&type=issues). This would mean a migration to `tmp_path` that is located at the same place as `tmpdir`, but is a `pathlib.Path` object.

What's your opinion on this?

**Comment by xflr6** [comment]
Yes: now that we have dropped Python 2 support, we can think about where/how to accept `pathlib.Path` objects whether to use them internally etc.

And yes, will also move tests fixtures from `tmpdir` to `tmp_path` (the former [knows a few more tricks](https://github.com/xflr6/graphviz/blob/04dcd57c699268105a47bbdc4ffc9c69657c7385/tests/test_tools.py#L21) though).

**Comment by xflr6** [comment]
Thanks for the PR. Closing stale issue for now. Let me know in case you want to continue to contribute here.
