### ISSUE TITLE
Convert graphviz.files.Source to graphviz.dot.Digraph

### ISSUE THREAD

**Issue by clayms** [xflr6/graphviz#130]
Is there a way to convert the `graphviz.files.Source` type to `graphviz.dot.Digraph` type?

I would like to import a `.gv` file and use it as a subgraph in another graph.

However, the following fails.

```python

from graphviz import Digraph, Source

g1 = Digraph('G', filename='hello.gv')
g1.edge('Hello', 'Earth')
g1.save("g1.gv")
g1
```
![image](https://user-images.githubusercontent.com/12793783/111315990-42636480-8639-11eb-9409-9c43da5e584f.png)

```python
g2 = Digraph('G', filename='hi.gv')
g2.edge('Hi', 'Moon')
g2
```
![image](https://user-images.githubusercontent.com/12793783/111316135-6030c980-8639-11eb-98c9-f95a97575c5e.png)

```python
g2.subgraph(g1)
g2
```
![image](https://user-images.githubusercontent.com/12793783/111316275-80608880-8639-11eb-98d0-8226dafde4ef.png)

```python
type(g1)
```

```
graphviz.dot.Digraph
```
____

```python
g1_file = Source.from_file(filename="g1.gv")
g1_file
```
![image](https://user-images.githubusercontent.com/12793783/111316445-a554fb80-8639-11eb-8890-f16e5a7abfac.png)

```python
type(g1_file)
```

```
graphviz.files.Source
```

### However, even though the imported `Source` file (`g1_file`) can be rendered the same as the in-memory `Digraph` (`g1`), it cannot be added as a subgraph as it is a `Source` object, not a `Digraph` object.

```python
g2 = Digraph('G', filename='hi.gv')
g2.edge('Hi', 'Moon')

g2.subgraph(g1_file)
```

```bash

g2.subgraph(g1_file)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
o:\_Projects\ArchitectureDiagrams\code\github_answers6.py in ()
----> 861 g2.subgraph(g1_file)

/home/user/.local/lib/python3.6/site-packages/graphviz/dot.py in subgraph(self, graph, name, comment, graph_attr, node_attr, edge_attr, body)
    215             raise ValueError('graph must be sole argument of subgraph()')
    216 
--> 217         if graph.directed != self.directed:
    218             raise ValueError('%r cannot add subgraph of different kind:'
    219                              ' %r' % (self, graph))

AttributeError: 'Source' object has no attribute 'directed'
```

**Comment by clayms** [comment]
Ok, figured it out

```python
from graphviz import Digraph, Source

g1_body = Source.from_file(filename="g1.gv").source.split('\n')[1:-2]
g1_digraph = Digraph(body=g1_body) 
g2.subgraph(g1_digraph)
g2
```

![image](https://user-images.githubusercontent.com/12793783/111375350-845dcc00-8674-11eb-87fe-261ab1b6a572.png)

**Comment by xflr6** [comment]
Thanks for documenting.

`Source` only loads (does not parse) the file, but as the `body` of `(Di)Graph` is a `list` of lines you can get away with operations on the list strings in simple cases.

See https://graphviz.readthedocs.io/en/stable/#see-also for libraries that parse DOT.

We could make `Source` iterable so one could do `list(<Source instance>)[1:-2]`.
