### ISSUE TITLE
Managing special characters

### ISSUE THREAD

**Issue by MonikaBarget** [xflr6/graphviz#132]
Graphviz can only handle alphanumerical characters and underscores, so it is necessary to "tokenize" texts with many special characters before applying data visualisation and put all strings to be treated as IDs into hyphens. 

Is there any recommended workflow or a recommended Python package that works best with graphviz?

**Comment by xflr6** [comment]
> Is there any recommended workflow or a recommended Python package that works best with graphviz?

This package `graphviz` here is actually a Python package to work with Graphviz (https://www.graphviz.org).

More are here: https://github.com/xflr6/graphviz#see-also

IIUC you are referring to the [DOT language](https://www.graphviz.org/doc/info/lang.html) syntax, more specifically on the aspect of quoting and escaping. This is something that is abstracted by this library (though quoting and escaping can be tricky so I won't promise there are no edge cases that I am not aware of):

```python
In [1]: import graphviz
   ...: 
   ...: d = graphviz.Digraph()
   ...: d.node('spam')
   ...: d.edge('spam', '"spam"')
   ...: d.edge('"spam"', 'späm')
   ...: 
   ...: print(d.source)
   ...: d
digraph {
	spam
	spam -> "\"spam\""
	"\"spam\"" -> "späm"
}
Out[1]: 
```

![spam](https://user-images.githubusercontent.com/6342379/112675988-2b5a1900-8e68-11eb-8e78-c59909e91933.png)

Hope that helps.
