### ISSUE TITLE
How to use splines=ortho

### ISSUE THREAD

**Issue by Ahorvath94** [xflr6/graphviz#133]
Hi Graphviz,

I was looking on the graphviz website and it is possible to render orthogonal lines busing graphviz. I am wondering if this is a capability for this python version? I want to have the output look something like this:
https://stackoverflow.com/questions/8939973/how-can-i-generate-rectangle-style-edges-instead-of-curves-in-graphviz

Thanks!

Alex

**Comment by xflr6** [comment]
Hi Alex.

> render orthogonal lines busing graphviz

See https://graphviz.readthedocs.io/en/stable/manual.html#styling

```python
In [1]: import graphviz
   ...: 
   ...: d = graphviz.Digraph(name='Orthogonal',
   ...:                      graph_attr={'label': 'Orthogonal edges',
   ...:                                  'splines': 'ortho',
   ...:                                  'nodesep': '0.8'},
   ...:                      node_attr={'shape': 'box'})
   ...: 
   ...: d.edges(['ab', 'ac'])
   ...: d.edges(['bd', 'be'])
   ...: d.edges(['cf', 'cg'])
   ...: 
   ...: d
Out[1]: 
````

![spam](https://user-images.githubusercontent.com/6342379/114706565-6c3ba400-9d29-11eb-828a-c6d883b741d4.png)
