### ISSUE TITLE
graphiz.Source and graphiz object are giving two different structures. 

### ISSUE THREAD

**Issue by ninjakx** [xflr6/graphviz#134]
```
from graphviz import Graph, Source
g = Graph('G', filename='process.gv', engine='sfdp')

g.edge('run', 'intr')
g.edge('intr', 'runbl')
g.edge('runbl', 'run')
g.edge('run', 'kernel')
g.edge('kernel', 'zombie')
g.edge('kernel', 'sleep')
g.edge('kernel', 'runmem')
g.edge('sleep', 'swap')
g.edge('swap', 'runswap')
g.edge('runswap', 'new')
g.edge('runswap', 'runmem')
g.edge('new', 'runmem')
g.edge('sleep', 'runmem')
g
```
![s1](https://user-images.githubusercontent.com/29797787/117351117-f7dcc680-aeca-11eb-9fbe-0b0fec9c6edb.png)

```
Source(g)
```
![s2](https://user-images.githubusercontent.com/29797787/117351134-fb704d80-aeca-11eb-805c-42f6254600b5.png)

Using `Source` graph more look like a tree.

**Comment by xflr6** [comment]
The [example](https://graphviz.readthedocs.io/en/stable/examples.html#process-py) uses `engine='sfdp'`, so you need to set the same engine if you want to reproduce with `Source` :

```python
>>> Source(g, engine='sfdp')
```

See also [graphviz-engines.ipynb](https://nbviewer.jupyter.org/github/xflr6/graphviz/blob/master/examples/graphviz-engines.ipynb) and [manual.html#engines](https://graphviz.readthedocs.io/en/stable/manual.html#engines).
