### ISSUE TITLE
Double-headed arrow style?

### ISSUE THREAD

**Issue by galenseilis** [xflr6/graphviz#144]
The following diagram was made with Graphviz. I wasn't able to reproduce the double-headed arrows, and I didn't see a solution in the [Examples](https://graphviz.readthedocs.io/en/stable/examples.html) or the [intro of the user guide](https://graphviz.readthedocs.io/en/stable/manual.html).

![https://semopy.com/files/example.png](https://semopy.com/files/example.png)

How can I produce double-headed arrows as a style for edges?

**Comment by xflr6** [comment]
See the exhaustive [upstream Graphviz docs on available attributes](https://www.graphviz.org/doc/info/attrs.html) (linked from [Basic usage](https://graphviz.readthedocs.io/en/stable/manual.html#basic-usage)).

You are probably looking for the [`dir` attribute](https://www.graphviz.org/docs/attrs/dir/):

```python
In [1]: import graphviz
   ...: 
   ...: g = graphviz.Graph()
   ...: 
   ...: g.edge('A', 'B', dir='both')
   ...: g
```
![spam](https://user-images.githubusercontent.com/6342379/140479273-1ea1627f-1ce8-4a7f-b7ff-46f23dfd457e.png)

If you manage to reproduce the graph (and it has an openly licence) maybe we could add it to the examples, WDYT?

**Comment by galenseilis** [comment]
Perfect! That is exactly what I want. Even better, I appreciate you providing the exhaustive Graphviz docs on the available attributes. Wonderful.

**Comment by xflr6** [comment]
Happy to help. :) Closing.
