### ISSUE TITLE
Connecting to subgraphs only works using fdp engine

### ISSUE THREAD

**Issue by NAThompson** [xflr6/graphviz#147]
Beginning with the [fdp](https://graphviz.readthedocs.io/en/stable/examples.html#fdpclust-py) cluster example, we see that we can attach edges to subgraphs. In the example, this figure is produced:

<img width="585" alt="Screen Shot 2021-11-10 at 12 59 02" src="https://user-images.githubusercontent.com/5459618/141192463-4caa9b3c-832c-4e61-916e-e5841cc5fbee.png">

However, the same code with the default engine, i.e., replacing

```python
g = graphviz.Graph('G', filename='fdpclust.gv', engine='fdp')
```

with

```
g = graphviz.Graph('G', filename='fdpclust.gv')
```

 produces a completely different graph:

<img width="776" alt="Screen Shot 2021-11-10 at 12 57 57" src="https://user-images.githubusercontent.com/5459618/141192313-1e9617c7-bde9-4ff0-9b64-93e029fea537.png">

Should an error be thrown in this case?

**Comment by xflr6** [comment]
From the upstream [source of the example](http://www.graphviz.org/Gallery/undirected/fdpclust.html), I think yes: cluster-to-cluster edges seem to be specific to the `fdp` engine:

> The fdp layout program supports edges between nodes and clusters and cluster-to-cluster. 

From https://graphviz.org/docs/attrs/compound/ I understand that `dot` supports related node-to-node edges that 'end early' on a cluster with `compound=true`.

You might want to ask about this upstream, e.g. in https://forum.graphviz.org (mildly related [upstream issue](https://gitlab.com/graphviz/graphviz/-/issues/1057)), closing.
