### ISSUE TITLE
Allow HTML tags in the middle of strings

### ISSUE THREAD

**Issue by codeofdusk** [xflr6/graphviz#148]
I'd like to be able to do something like:

```python
g = graphviz.Digraph()
g.node("a", "TP")
g.node("b", "DP")
g.node("c", "D<br/>I")
g.edge("a", "b")
g.edge("b", "c")
```

And have a newline appear between "D" and "I" in the label of node c.

**Comment by xflr6** [comment]
AFAICT, this is supported (cf. [manual.html#quoting-and-html-like-labels](https://graphviz.readthedocs.io/en/stable/manual.html#quoting-and-html-like-labels), also: upstream [docs on HTML-like labels](https://graphviz.gitlab.io/doc/info/shapes.html#html)):

```python
In [1]: import graphviz
   ...: 
   ...: g = graphviz.Digraph()
   ...: 
   ...: g.node('a', 'TP')
   ...: g.node('b', 'DP')
   ...: g.node('c', '<D<br/>I>')
   ...: 
   ...: g.edge('a', 'b')
   ...: g.edge('b', 'c')
   ...: 
   ...: g
```

![spam](https://user-images.githubusercontent.com/6342379/141684138-b3c2d130-5f62-4f81-b35d-a981a9bcf941.png)

Another option is using [manual.html#backslash-escapes](https://graphviz.readthedocs.io/en/stable/manual.html#backslash-escapes):

`g.node('c', r'D\nI')`
