### ISSUE TITLE
Arrowhead style only applied to one side

### ISSUE THREAD

**Issue by galenseilis** [xflr6/graphviz#151]
I would like to use double-headed arrows. Preferably one end of the arc would be `lnormal` and the other `rnormal`, but at least having the half-headed styles on both ends would be desired. Here is a minimal example that reproduces my issue.

```python
from graphviz import Digraph 
g = Digraph()

g.edge('a', 'b', arrowhead='lnormal', dir='both')
g.view()
```

![image](https://user-images.githubusercontent.com/11385121/144685557-b13c4e21-cee6-4743-b1d3-4f1ee2b89c88.png)

**Comment by xflr6** [comment]
See [upstream docs on `dir`](https://www.graphviz.org/docs/attrs/dir/) (attributes section linked from https://graphviz.readthedocs.io/en/stable/manual.html#styling):

> The actual style of the arrowhead can be specified using the `arrowhead` and `arrowtail` attributes.

```python
import graphviz

dot = graphviz.Digraph()
dot.edge('a', 'b', arrowhead='lnormal', arrowtail='lnormal', dir='both')
dot
```
![spam](https://user-images.githubusercontent.com/6342379/144706792-e837e031-425d-47f6-9396-ee87fda75f76.png)

```python
import graphviz

dot = graphviz.Digraph()
dot.edge('a', 'b', arrowhead='lnormal', arrowtail='rnormal', dir='both')
dot
```
![spam](https://user-images.githubusercontent.com/6342379/144706824-3a04c9c6-9011-49b5-8089-2e335ce23c79.png)

**Comment by galenseilis** [comment]
Wonderful, thank you!
