### ISSUE TITLE
Support for {rank: <rank>; [<node_id>;]+}

### ISSUE THREAD

**Issue by cpopescu** [xflr6/graphviz#154]
Sometimes is useful to enforce the same rank on a group of nodes (or subgraphs) using something like the structure described in the subject. E.g. compare
```
digraph G {
  a; b; c; d;
  a -> b; b->c; a->d;
}
``` 
with
```
digraph G {
  a; b; c; d;
  a -> b; b->c; a->d;
  { rank = same; a; b }
}
```

I couldn't find how to do it with current API - Is it possible to add support for that? (e.g. `dot.rank('same', ['a', 'b'])` or similar)

Thanks a lot !

cp

**Comment by xflr6** [comment]
Does https://graphviz.readthedocs.io/en/stable/examples.html#rank-same-py help (mentioned in [attributes docs](https://graphviz.readthedocs.io/en/stable/manual.html#attributes))?

**Comment by xflr6** [comment]
```python
import graphviz

dot = graphviz.Digraph()

with dot.subgraph() as s:
    s.attr(rank='same')
    s.node('a')
    s.node('b')

dot.node('c')
dot.node('d')

dot.edges(['ab', 'bc', 'ad'])

dot
```

![spam](https://user-images.githubusercontent.com/6342379/146686158-8bce2c40-3ba9-4fb0-94f5-b3df26a6630b.png)
