### ISSUE TITLE
labelfloat seems not to function

### ISSUE THREAD

**Issue by cicocn** [xflr6/graphviz#16]
```
# Graph 2, pilot research
d = Digraph('Pilot Research', 'Interaction between EGA, tranSMART and GALAXY', 'E_T_G.pdf', format='pdf',node_attr={'shape': 'ellipse'})
d.node('EGA')
d.node('tranSMART')
d.node('Galaxy')
d.edge('EGA','tranSMART',label = 'mapping',labelfloat = 'true')
d.edge('EGA','Galaxy',label='processing', labelfloat = 'true')
d
```
It seems that 'labelfloat' doesn't work. Is there any mistake in my code?

**Comment by xflr6** [comment]
Can you specify what exactly does not work as expected?

Running your code, I get the following `d.source`:

```
// Interaction between EGA, tranSMART and GALAXY
digraph "Pilot Research" {
	node [shape=ellipse]
		EGA
		tranSMART
		Galaxy
			EGA -> tranSMART [label=mapping labelfloat=true]
			EGA -> Galaxy [label=processing labelfloat=true]
}
```

Is this different from what you wanted?

The `filename` argument of `Digraph` is the name of the DOT source file: I propose changing that to `E_T_G.gv` or similar.

**Comment by cicocn** [comment]
[image: Inline image 1]
Here is the picture, I don't find the difference between with labelfloat
and without it.

**Comment by xflr6** [comment]
See the [Graphviz docs](http://www.graphviz.org/doc/info/attrs.html#d:labelfloat) on `labelfloat`:
```
If true, allows edge labels to be less constrained in position.
In particular, it may appear on top of other edges.
```
You might only get a visible layout change, if you have a dense graph with lots of edges.

Closing: concerns rendering inside the [Graphviz](http://www.graphviz.org) backend, not the Python interface provided here.
