### ISSUE TITLE
Link formatting

### ISSUE THREAD

**Issue by EastBayEv** [xflr6/graphviz#160]
Just a quick heads-up that the output of 

```tf.keras.utils.plot_model(classifier_model)```

for this tutorial https://www.tensorflow.org/text/tutorials/classify_text_with_bert, returns: 

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.

... if pydot and graphviz are not installed. 

However, the url does not work by clicking because the closed parenthesis is part of the hyperlink. Have a nice day!

**Comment by xflr6** [comment]
Sorry, but I think you got the wrong project for reporting this: did you mean to report this at https://github.com/tensorflow/tensorflow/issues?

https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/keras/utils/vis_utils.py#L103-L107

Side note that the tensorflow message is not about this library: https://github.com/xflr6/graphviz#see-also
