### ISSUE TITLE
can I viz the node gain&cover in trees?

### ISSUE THREAD

**Issue by riaris** [xflr6/graphviz#161]
I find graphviz can viz the tree. however, it is only node and leaf. when I use Booster.get_dump(fmap='',dump_format='text',with_stats=True) I can get the gain&cover. how can I viz the gain&cover on trees?

**Comment by xflr6** [comment]
I am not sure if this is about this library here (or rather about [xgdboost](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.Booster.get_dump)?).

Not sure what you mean by 'gain & cover': can you provide more detail or a minimal reproducible example?

**Comment by riaris** [comment]
sure I mean xgboost, can I draw that in the tree result?

Sebastian Bank ***@***.***> 于2022年3月2日周三 17:55写道：

**Comment by xflr6** [comment]
> sure I mean xgboost

You seem to be in the wrong place (maybe you mean https://github.com/dmlc/xgboost/issues?), closing.

**Comment by riaris** [comment]
Got it, thank you!

**Comment by riaris** [comment]
Got it, Thank you!

Sebastian Bank ***@***.***> 于2022年3月3日周四 17:24写道：
