### ISSUE TITLE
ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

### ISSUE THREAD

**Issue by szeynepblt** [xflr6/graphviz#162]
Hi,

I'm getting this error. And I've searched for this in stackoverflow. I've realized, graphviz hadn't loaded on windows. And after that, graphviz 2.50 loaded on windows with system path (anaconda version is 2.38, i didn't find 2.38 windows exe) but i'm still getting this error. How can i use graphviz in python?

**Comment by xflr6** [comment]
If you are using Anaconca, you need to `conda install -c conda-forge python-graphviz` AFAIU (which also installs Anaconda's distribution of graphviz.org).

If you are using regular Python, you might need to add the `bin/` directory of  your graphviz.org installation to your PATH (in case the installer did not do that).

See https://graphviz.readthedocs.io/en/stable/manual.html#installation for details.
