### ISSUE TITLE
How to control the points of splines?

### ISSUE THREAD

**Issue by Alexyrt** [xflr6/graphviz#165]
Hi, all.

The documentation of “splineType” as follows.

splineType
spline ( ';' spline )*

where spline = (endp)? (startp)? point (triple)+
and triple = point point point
and endp = "e,%f,%f"
and startp = "s,%f,%f"
If a spline has points p₁ p₂ p₃ … pₙ, (n = 1 (mod 3)), the points correspond to the control points of a cubic B-spline from p₁ to pₙ. If startp is given, it touches one node of the edge, and the arrowhead goes from p₁ to startp. If startp is not given, p₁ touches a node. Similarly for pₙ and endp.

But the following codes don’t work.

#Python3.6
dot1 = Digraph(“1”)
dot1.attr(rankdir=‘LR’)
dot1.graph_attr[‘layout’] = ‘neato’ #fdp,neato
dot1.graph_attr[‘splines’] = ‘true’ #compound,curved,true

dot1.node(‘a’,shape=“point”,pos=“0,0!”,color=“blue”)
dot1.node(‘b’,shape=“point”,pos=“10,0!”,color=“green”)
dot1.node(‘c’,shape=“point”,pos=“5,5!”,color=“red”)

dot1.edge(‘a’,‘b’,pos=‘10,0 0,0 1,1 2,2 3,3 5,5 7,3 8,2 9,1’)  #It doesn’t work.

dot1.view()

I have tried
“dot1.edge(‘a’,‘b’,pos=‘10,0 0,0 1,1 2,2 3,3 5,5 7,3 8,2 9,1’)”
“dot1.edge(‘a’,‘b’,pos=‘e,10,0 s,0,0 1,1 2,2 3,3 5,5 7,3 8,2 9,1’)”
in python, but they don’t work neither.

The results are all straight line.

Does anyone know the correct expression to guide the spline in python?
Thanks a lot!

**Comment by xflr6** [comment]
AFAIU this is similar to https://stackoverflow.com/questions/70378702.

From the answer, I understand you need the `-n[num]` flag (https://graphviz.org/faq/#FaqDotWithCoords) for this to work.

This flag is not (yet) supported by this libary (open feature request in #131, PR welcome):

```python
import subprocess

import graphviz

dot = graphviz.Digraph(name='splines',
                       graph_attr={'layout': 'neato', 'splines': 'true'},
                       node_attr={'shape': 'point'})

dot.node('a', pos='0,0!', color='blue')
dot.node('b', pos='100,0!', color='green')
dot.node('c', pos='50,50!', color='red')

dot.edge('a', 'b', pos='0,0 30,66 70,60 100,0')

path = dot.save()

subprocess.run(['dot', '-n2', '-Tpng', '-O', path])
```
![splines gv](https://user-images.githubusercontent.com/6342379/160710381-325561f2-9cca-4acd-8570-8e3feea3ae8d.png)

**Comment by Alexyrt** [comment]
Hello, sorry to bother you again.
I can control the points of splines now with your help and thank you very much!
But I have another question. Why the attributes of edge such as 'dir', 'headport', 'tailport' are not work, especially 'dir' ?
Here are my codes.


import subprocess


import graphviz


dot = graphviz.Digraph(name='splines',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;graph_attr={'layout': 'neato', 'splines': 'true'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;node_attr={'shape': 'circle', 'height': '0.2'})


dot.node('a', pos='0,0!', color='blue')
dot.node('b', pos='150,0!', color='green')


dot.edge('a', 'b', dir='both', headport='s',tailport='s', pos='0,18 40,66 80,60 150,18')


path = dot.save()


subprocess.run(['dot', '-n2', '-Tpng', '-O', path])



The arrows are missing.



And here is the final graph I want, do you think&nbsp;graphviz is the best library to make this? [lol]

**Comment by xflr6** [comment]
Hi Alex,

I get the same result that no arrows are visible when rendering your example (even though you specify `dir='both'` on the edge).

Could it be that the manually placed nodes are over the arrows (if you remove the `pos=...`part, the arrows are visible)?

> Do you think graphviz is the best library to make this?

AFAIU a better place for these kinds of questions ('how do I get to result X with DOT?') would be upstream https://forum.graphviz.org (they don't seem to be specific to the Python wrapper we provide here any more), I hope you understand.
