### ISSUE TITLE
Semitransparent, thick edges are not rendered properly

### ISSUE THREAD

**Issue by BenPortner** [xflr6/graphviz#183]
The renderer does not render edges properly if both edge transparency (color alpha channel) and penwidth are modfied, see example below. The error seems to occur for all image output formats (tested gif, bmp, jpeg)

```dot
digraph {
"A" -> "B" [color="#00000080", penwidth="20"] 
"C" -> "B" [color="#00000080", penwidth="10"] 
}
```
![graph2](https://user-images.githubusercontent.com/52913510/203080493-febed496-1cb1-4681-98d4-4e38ce655f32.gif)

Produced using Graphviz v.6.0.1 build h8f5d4a1_0 (most recent version on [conda-forge](https://github.com/conda-forge/graphviz-feedstock)).

**Comment by xflr6** [comment]
Thanks. AFAICT this is an upstream issue (something in https://www.graphviz.org -- not specific to the Python wrapper here).

Please report upstream: https://gitlab.com/graphviz/graphviz/-/issues
