### ISSUE TITLE
Is there a way to have squared edges?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [xflr6/graphviz#186]
Hi!

I would like to know if there's a way to draw diagrams with squared edges between nodes?

In the examples, I've only seen round egdes or straight lines.

Thanks in advance!

**Comment by xflr6** [comment]
Hi. If you have general questiona about http://graphviz.org/ (as oposed to this Python interface), https://forum.graphviz.org/ might be a beter place to ask.

Maybe this helps? https://www.graphviz.org/doc/info/attrs.html#d:splines

Closing (off-topic).
