### ISSUE TITLE
What is doctest_mark_exe() ?

### ISSUE THREAD

**Issue by wdrum** [xflr6/graphviz#188]
The function doctest_mark_exe() appears frequently in the documentation, such as [here](https://pypi.org/project/graphviz/) and [here](https://graphviz.readthedocs.io/en/stable/index.html?highlight=doctest_mark_exe), but it is difficult (for me, at least) to find an explanation of it. Does anyone know what it does?
Thanks.

**Comment by xflr6** [comment]
See #172.

**Comment by xflr6** [comment]
See https://github.com/xflr6/graphviz/issues/172#issuecomment-1778710810
