### ISSUE TITLE
Digraph node API: rename `name` argument to `node_id`

### ISSUE THREAD

**Issue by NAThompson** [xflr6/graphviz#191]
The `help(Digraph.node)` returns the following:

```
node(self, name: str, label: Optional[str] = None, _attributes=None, **attrs) -> None
    Create a node.

    Args:
        name: Unique identifier for the node inside the source.
        label: Caption to be displayed (defaults to the node ``name``).
        attrs: Any additional node attributes (must be strings).
```

Semantically, it feels like the kwargs should be `node(uid="foo_uid", label=""....)`, as `name` does not visually indicate to the reader that the `name` must be unique.

Another suggestion is to change the argument to `unique_name`.

graph.edge has a similar issue.

**Comment by xflr6** [comment]
Can you clarify where the term `uid` stems from (the [DOT grammar](https://www.graphviz.org/doc/info/lang.html) calls it `node_id`)? Maybe easy to confuse with `uuid`?

> Semantically, it feels like the kwargs should be `node(uid="foo_uid", label=""....)`

I am wondering why you want to pass this argument by keyword.

With the advent of https://peps.python.org/pep-0570, I think we might rather make it positional-only (after dropping Python 3.7).

What you are proposing is a backwards-incompatible, so I think there should be a high bar for this kind of change.

**Comment by xflr6** [comment]
Using the same names as the DOT grammar would be nice if we just created this library. However, it would be backwards-incompatible for existing users that do pass the argument by keywords (which I would tend to discourage, rather making the argument positional-only once this is possible). In sum, I don't think we should do it for now.
