### ISSUE TITLE
Digraph.node() cannot merge nodes with the same name

### ISSUE THREAD

**Issue by Leepay** [xflr6/graphviz#192]
my code are:
```python
from graphviz import Digraph
dot = Digraph(comment='test')
dot.node('A', shape="box")
dot.node('A', shape="box")
dot.node('A')
dot.node('A')
print(dot.source)
```
Output is:
```text
// test
digraph {
	A [shape=box]
	A [shape=box]
	A
	A
}
```
But the expected output should be a digraph with only one node, which is 'A', isn't it?

My environment:
```
python 3.8.13
graphviz 2.50.0
```

**Comment by xflr6** [comment]
> But the expected output should be a digraph with only one node, which is 'A', isn't it?

No. DOT-building methods such as `.node()` and `.edge()` precisely add node-statements and edge-statements to the DOT instance (not sure if this should be more explicit in the documentation).

`graphviz.Graph` and `graphviz.Digraph` do not track the semantics of the statements added (e.g. which nodes have been added): Their sole purpose is to simply to generate DOT source line by line.
