### ISSUE TITLE
CLI option `--graph-output` not working in 2.5.0

### ISSUE THREAD

**Issue by ealtamir** [xflr6/graphviz#193]
When I run version 2.5.0 in a fresh python install I get the following:

```
pipdeptree --graph-output png
flowchart TD
    classDef missing stroke-dasharray: 5
    graphviz[graphviz\n0.20.1]
    pip[pip\n22.3.1]
    pipdeptree[pipdeptree\n2.5.0]
    setuptools[setuptools\n65.5.0]
```

When I downgrade to version 2.3.3 and I runt the same command, I get the expected output.

**Comment by xflr6** [comment]
Hey, it seems you want to report an error in [pipdeptree](https://pypi.org/project/pipdeptree/) and not in this package (`graphviz`, of which there are no versions `2.*` yet). You are probably looking for https://github.com/tox-dev/pipdeptree/issues
