### ISSUE TITLE
windows error: cannot name a file as piping.py？

### ISSUE THREAD

**Issue by redreamality** [xflr6/graphviz#194]
Got this error when installing this package.
`ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Users\\o0oii\\AppData\\Roaming\\Python\\Python39\\site-packages\\graphviz\\piping.py'
Check the permissions.`

It's weird that windows cannot name a file as piping.py?  
![image](https://user-images.githubusercontent.com/3147776/221345159-8dcac985-c126-4a77-951c-a3bf9a551324.png)

**Comment by xflr6** [comment]
Can you provide information on how exactly you are trying to install `graphviz` and on the target system?

> It's weird that windows cannot name a file as piping.py?

I don't think that the file name is the reason you get `OSError: [Errno 13] Permission denied`, but rather the permissions of the directory tree you are trying to install in vs. the permissions that the installation was started with.

See https://graphviz.readthedocs.io/en/stable/manual.html#installation:

> For a system-wide install, this typically requires administrator access. For an isolated install, you can run the same inside a [venv](https://docs.python.org/3/library/venv.html#module-venv) or a [virtualenv](https://virtualenv.pypa.io/).

On Windows, this usually means that the shell ( `cmd`, PowerShell) used to `pip install` must be `run as Adminitstrator`.

`pip` also has https://pip.pypa.io/en/stable/user_guide/#user-installs

**Comment by redreamality** [comment]
![image](https://user-images.githubusercontent.com/3147776/221362772-6d345efb-435a-4b60-9eed-26a874641ca4.png)

the Chinese character on the topleft red box means that the cmd is `running as Adminitstrator`

Other useful infos/evidences:
![image](https://user-images.githubusercontent.com/3147776/221362900-00ce218d-e91b-440e-a232-97e0ca4c960b.png)
All other file except the `piping.py` is properly installed.


system specs:
windows 21H2
22000.739
AMD Ryzen 7 Microsoft Surface (R) Edition   2.00 GHz

**Comment by redreamality** [comment]
found reason,  close huorong anti-virus
