### ISSUE TITLE
Render with transparent background?

### ISSUE THREAD

**Issue by galenseilis** [xflr6/graphviz#195]
For my blog I would like to render graphviz diagrams in PNG format of models I've trained in PyMc. Is there a way to make the background canvas transparent?

Here is an example from [pymc](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.model_to_graphviz.html)

```python
import numpy as np
from pymc import HalfCauchy, Model, Normal, model_to_graphviz

J = 8
y = np.array([28, 8, -3, 7, -1, 1, 18, 12])
sigma = np.array([15, 10, 16, 11, 9, 11, 10, 18])

with Model() as schools:

    eta = Normal("eta", 0, 1, shape=J)
    mu = Normal("mu", 0, sigma=1e6)
    tau = HalfCauchy("tau", 25)

    theta = mu + tau * eta

    obs = Normal("obs", theta, sigma=sigma, observed=y)

model_to_graphviz(schools)
```

**Comment by xflr6** [comment]
I don't know `pymc`, but from the API I understand you can modify the result of `model_to_graphviz()` (a `graphviz.Digraph`).
See https://graphviz.org/doc/info/attrs.html#d:bgcolor (I did not verify the transparency):

```python
import graphviz

dot = graphviz.Digraph()

dot.edge('hello', 'world')
dot
```
![spam1](https://user-images.githubusercontent.com/6342379/222520075-2a6fe027-f4a8-478c-8d5a-6ede54787763.png)

```python
dot.attr(bgcolor='transparent')
dot
```

![spam2](https://user-images.githubusercontent.com/6342379/222520116-2ee07c9d-779f-4d08-9bf6-d28a8d4f977b.png)

```python
dot.attr(bgcolor='green')
dot
```

![spam3](https://user-images.githubusercontent.com/6342379/222520175-4c530c28-d3b9-4821-8f3b-b4d188d445dc.png)
