### ISSUE TITLE
Strict Graph

### ISSUE THREAD

**Issue by BenjaminBoehm** [xflr6/graphviz#20]
Hey,
I'm wondering why there is no support for the 'strict' option of graphs.
Is there reason that you don't want to implement it?
I changed it in my local library and I'm considering to commit these changes.

Thanks

**Comment by xflr6** [comment]
Thanks, I must have overlooked that, would definitely be nice to add.

Do you use separate subclasses or a creation argument? Not quite sure what would be better at tfirst sight. Can strict/nonstrict graphs be nested into each other or is it more like `Graph` vs. `Digraph`?

**Comment by BenjaminBoehm** [comment]
I just added the strict as option to the dot class:
```python
def __init__(self, name=None, comment=None,
            filename=None, directory=None,
            format=None, engine=None, encoding=None,
            graph_attr=None, node_attr=None, edge_attr=None, body=None, strict=False):
```

and simply
```python
head = self._subgraph if subgraph else self._head
if self.strict:
             head = 'strict ' + head
```
It really just adds 'strict' in front of the dot graph so it is possible to also nest them into each other.

**Comment by xflr6** [comment]
Allright, 06af6e41d1fd9f8ff3e832438dbc612ef7c51c55 does that. Closing (new release might take a while).
