### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by jjhesk** [xflr6/graphviz#201]
I have built gv file with 16000 edges.
I got an error from this

abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

Are any ways to tune this program to be more memory efficient?
https://graphviz.org/doc/info/command.html

**Comment by xflr6** [comment]
Hey, looks like this is about an issue in upstream https://www.graphviz.org (not in the Python wrapper here).

See https://gitlab.com/graphviz/graphviz/-/issues or https://forum.graphviz.org.
