### ISSUE TITLE
NameError: name 'doctest_mark_exe' is not defined

### ISSUE THREAD

**Issue by suryasiriki4** [xflr6/graphviz#208]
erro when using 
`doctest_mark_exe()`

[reference link](https://forum.graphviz.org/t/unable-to-execute-an-example-in-official-site-doctest-mark-exe-is-not-defined/1490)

**Comment by xflr6** [comment]
See #172.

Maybe we can add a note to their first occurrence in `README.md`  and in https://graphviz.readthedocs.io/en/stable/manual.html

**Comment by xflr6** [comment]
See https://github.com/xflr6/graphviz/issues/172#issuecomment-1778710810, closing.
