### ISSUE TITLE
Issues with Install at dot.render()

### ISSUE THREAD

**Issue by danaoira** [xflr6/graphviz#21]
Hello,

This might be novice question, but I've been trying to test the tutorial for Python GraphViz to no avail.

I get errors when rendering the ```dot.render('test-output/round-table.gv', view=True)``` portion.

![image](https://cloud.githubusercontent.com/assets/2514403/12973238/c48b6d12-d05f-11e5-98aa-5a781490930f.png)

![image](https://cloud.githubusercontent.com/assets/2514403/12973362/b167cc7a-d060-11e5-84c0-2fa63de8ebb2.png)

I added the following to my System Environment PATH:
```
C:\Program Files (x86)\Graphviz2.38\bin
C:\Program Files (x86)\Graphviz2.38\
C:\Python35\
C:\Python35\Scripts
```

And still the does not point to the proper files, even if I point explicitly to the file path: ```dot.render('c:/...test-output/round-table.gv', view=True)```. I get a "path too long" error.

I'm assuming that the .gv is the DOT code we save from the output code that's generated? Please correct me if I'm wrong, because the tutorial wasn't very clear on that part.

Any help will be greatly appreciated. I've been taught that half the struggle is properly setting up the environment.

Thank you!

**Comment by danaoira** [comment]
Never mind, it works now. :)

**Comment by Raidez** [comment]
Hello, I have the same problem, so can you tell me how did you resolve your own problem ? pls °w°

**Comment by IamSphiwe** [comment]
How did you fix it?
