### ISSUE TITLE
Edge labels overlap with edges

### ISSUE THREAD

**Issue by eroell** [xflr6/graphviz#216]
Hi,
Thanks for this nice package!

One thing I came across multiple times is the overlap of edge labels with edges, in a super simple case:
```
import graphviz
dot = graphviz.Digraph()

node_texts = ["node text 1", "node text 2"]
edge_texts = ["edge text"]

for i, text in enumerate(node_texts):
    dot.node(name=str(i), label=text, shape="box", fontcolor="black")

for i, op in enumerate(edge_texts):
    # adding whitespace seems to be the only way of having no overlap between label and edge
    dot.edge(str(i), str(i + 1), label=f"{op}", fontcolor="black")
dot
```
![graphviz_1](https://github.com/xflr6/graphviz/assets/65244425/d37b7c25-2580-4c2e-b097-4a6d7fc30833)

My workaround for now is to add whitespaces before the label:
```
import graphviz
dot = graphviz.Digraph()

node_texts = ["node text 1", "node text 2"]
edge_texts = ["edge text"]

for i, text in enumerate(node_texts):
    dot.node(name=str(i), label=text, shape="box", fontcolor="black")

for i, op in enumerate(edge_texts):
    # adding whitespace seems to be the only way of having no overlap between label and edge
    dot.edge(str(i), str(i + 1), label=f"    {op}", fontcolor="black")
dot
```
![graphviz2](https://github.com/xflr6/graphviz/assets/65244425/a5a6d0c2-3002-46a3-bcb6-6fc8965776ff)

The other solutions I tried (that is, ChatGPT suggested) seemed not to work.

Is there somehow a proper way of handling this somehow?

Best,

**Comment by xflr6** [comment]
Thanks. :)

I tried a bunch of different attributes from https://www.graphviz.org/doc/info/attrs.html but it seems like using space in the label like you do in the workaround is the only thing that works.

https://stackoverflow.com/questions/12934763/graphviz-edge-label-too-close-to-another-edge seems to come to the same conclusion.

Maybe it's worth asking in the upstream Graphviz forum: https://forum.graphviz.org (should be where the experts on such questions hang out).

Cheeers

**Comment by eroell** [comment]
Thanks for the reply! Yes, tried those attributes as well...
For me that's enough for now so I'll probably leave it at that (and close the issue unless you want to keep it open?), but would get back to the Graphviz forum if it pops up again

**Comment by xflr6** [comment]
Sounds good, yep, let's close :)

Good luck.
