### ISSUE TITLE
Option for modifying attributes of existing nodes, edges...

### ISSUE THREAD

**Issue by kritinsai** [xflr6/graphviz#22]
To modify an attribute of an existing node, the same node requires to be added again, this creates an extra line in the dot source. For many modifications, the file size of the source grows unnecessarily.
So, can there be an extra method for modifying the attributes of existing edges or nodes ( possibly removing the line from graph.body and adding a new line with the modified attribute ) ?

**Comment by xflr6** [comment]
No really. The idea of the library is to stick to creating and rendering DOT source for visualization, not to provide a generic API for representing graphs (like e.g. NetworkX). Thereby `Graph` and `Digraph` can essentially be simple *append-only* list of strings with DOT code (no objects keeping track of individual nodes, edges, attributes etc.).

Typically, users already have the (information about the) collection of nodes and edges they want to render somewhere inside *their* objects/data structures (separation of concerns, why duplicate?). Wouldn't it be cleaner to make/use you own modifiable node objects that then use `graphviz` for rendering under the hood (composition).

You can also try `pygraphviz` or `pydot`, which AFAIR implement modifiable DOT elements (which makes more sense for them, as they also *parse* DOT code, i.e. do a full round-trip).
