### ISSUE TITLE
[Bug]Doesn't print the vertical bar if uses f-string

### ISSUE THREAD

**Issue by rafaeljcd** [xflr6/graphviz#223]
[Notebook Sample from repo](https://github.com/rafaeljcd/graphviz-sample/blob/main/sample.ipynb)

```python
dotA = Digraph(format="svg", graph_attr={"rankdir": "LR"})

x = 1
y = 2.0
dotA.node(
    name="A",
    label=f"{x}|Data {y:.4f}",
    shape="record",
)
dotA
```

Results in the following below which is not intended

<img width="150" alt="image" src="https://github.com/xflr6/graphviz/assets/123484899/052708b9-165e-48fd-92cc-1a6382b276bd">

While using the old string formatting of python

```python
dotB = Digraph(format="svg", graph_attr={"rankdir": "LR"})

dotB.node(
    name="B",
    label="{ %s | data: %.4f }" % (1, 2.0),
    shape="record",
)
dotB
```

Results in the desired format

<img width="169" alt="image" src="https://github.com/xflr6/graphviz/assets/123484899/1c0e2d78-6fb6-440f-9cd4-59b2d2173bdd">

**Comment by xflr6** [comment]
Hey. Sorry, but I don't understand where you see a possible bug within `graphviz` here.

IIUC this is the value you want to pass as `label`:

```python
>>> x = 1
>>> y = 2.0
>>> print('{ %s | data: %.4f }' % (x, y))
{ 1 | data: 2.0000 }
```

Clearly you are not getting this result with `f'{x} | data: {y:.4f}'` you are using above (no curly braces in your f-string).

This is as expected, right? Maybe you are just asking how to create the literal curly braces with a [Python f-string](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals)?

That would be `f'{{ {x} | data: {y:.4f} }}'` (need to be doubled).
