### ISSUE TITLE
Tooltip not work at any level (Graph, Node, Edge)

### ISSUE THREAD

**Issue by bikeridercz** [xflr6/graphviz#227]
Dear friends, I'm trying to use tooltips however it seems to not work ;-) Example follows:
```
...
    graph = Digraph(name = f'{process} process step dependencies', tooltip = gt)
    graph.attr(rankdir = 'LR')
    ...
        graph.node(name = n, label = l, tooltip = nt)
        graph.edge(tail_name = s, head_name = t, label = l, tooltip = et)
...

```

**Comment by xflr6** [comment]
Can you maybe provide a minimal reproducible example (your's e.g. has a couple of undefined variables)?

I can see tooltips in the output when rendering with `graph.render(format='svg')`, cf. https://graphviz.org/docs/attrs/tooltip/;

> Note: `cmap`, `svg` only.

**Comment by xflr6** [comment]
````python
import graphviz

s = graphviz.Source( '''
digraph {
  label="Graph Label"
  tooltip="Graph Tooltip"
  subgraph cluster_a {
    label="Cluster Label"
    tooltip="Cluster Tooltip"
    Node1 [tooltip="Node1 Tooltip"]
    Node1 -> Node2 [label="Edge" tooltip="Edge Tooltip"]
  }
}
''')

s.render(format='svg')
````
![Source gv](https://github.com/user-attachments/assets/1ddbfe04-9aeb-41c2-852b-7ea3644456fd)

I see tooltips when opening this SVG in a separate window and hovering over it.

**Comment by bikeridercz** [comment]
OK, here is an example

```
from graphviz import Digraph, Graph
import base64

graph = Digraph(name = 'TEST diagram')
graph.attr(rankdir = 'LR')

graph.attr('node', shape = 'box')
graph.node(name = 'SYSTEM_1', label = 'SYSTEM_1', tooltip = 'tooltip SYSTEM_1')
graph.node(name = 'SYSTEM_2', label = 'SYSTEM_2', tooltip = 'tooltip SYSTEM_2')

graph.attr('edge', style = "dashed")
graph.edge(tail_name = 'SYSTEM_1', head_name = 'SYSTEM_2', label = 'connection from SYSTEM_1 to SYSTEM_2', tooltip = 'connection tooltip ...')

graph_svg = graph.pipe(format="svg")
graph_svg_base64 = base64.b64encode(graph_svg).decode("utf-8")
```

then the picture is displayed on HTML page in this way ...
` <img class="img__graph" src="data:image/svg+xml;base64,{{ graph_svg_base64|safe }}" />

Picture is ok but without working tooltips ... means hover with mouse does not display anything

**Comment by xflr6** [comment]
AFAICT, the `graphviz` part works as expected:

```python
import graphviz

dg = graphviz.Digraph(name='TEST diagram', format='svg')
dg.attr(rankdir='LR')
dg.attr('node', shape='box')
dg.node('SYSTEM_1', label='SYSTEM_1', tooltip='tooltip SYSTEM_1')
dg.node('SYSTEM_2', label='SYSTEM_2', tooltip='tooltip SYSTEM_2')
dg.attr('edge', style='dashed')
dg.edge('SYSTEM_1', 'SYSTEM_2',
        label='connection from SYSTEM_1 to SYSTEM_2',
        tooltip = 'connection tooltip ...')

print(dg.pipe().decode('utf-8'))
dg.render()
```

Checking the SVG source output printed above, I find tooltip elements such as `<a xlink:title="tooltip SYSTEM_1">`.

> `<img src="data:image/svg+xml;base64,{{ graph_svg_base64|safe }}" />`

That might be the issue: IIUC `<img>` will not display tooltips from inside. I see them using `<object data="*.svg">` in a HTML page instead. Another option might be to directly embed the `<svg>` code (I am no expert on this).

**Comment by bikeridercz** [comment]
Yes graphviz part is OK. Thanks for help !

**Comment by bikeridercz** [comment]
You were right, sending result of `graph_svg = graph.pipe(format = "svg")` from backend to HTML page gives good result with working tooltips. However there are few extra non-html characters like `\b \n ...`. See picture ...

<img width="864" alt="image" src="https://github.com/user-attachments/assets/03cb8c36-7f2a-402e-a91f-da4d7c4d6d0a" />


As you can see there is `\b` at the beginning and lot of subsequent` \n `characters in code generated by pipe method, see sample of generated code ...

`b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<!-- Generated by graphviz version 12.1.2 (20240928.0832)\n -->\n<!-- Title: cetin.flexi.d&#45;1 process step dependencies Pages: 1 -->\n<svg width="538pt" height="75pt"\n ...`

So the question is how to get a pure `<svg> ... </svg>` code to be insertable into HTML page easily ;-)
