### ISSUE TITLE
how to add the edge width attribute?

### ISSUE THREAD

**Issue by suchee** [xflr6/graphviz#23]
I understand that when adding an edge adding additional attributes is allowed. However, I think this is not working. For instance, "penweight" is the attribute to set the width of the edge. it does not work, can you help?

import graphviz as gv
g1 = gv.Digraph(format='pdf')
g1.node("A")
g1.node("B")
g1.edge("A","B", label="test",penweight="5.00")
g1.view()

**Comment by xflr6** [comment]
I think this concerns underlying Graphviz and not this libary (closing). Anyway, I think the attribute name may simply be `penwidth`, see http://www.graphviz.org/doc/info/attrs.html#d:penwidth

**Comment by vak** [comment]
is there anything working with `_attributes`?

this is also not working: `my_digraph_.edge('from_node', 'to_node', shape = "box")`

**Comment by xflr6** [comment]
Hi vak.

Not sure I understand. See the [table of Node Edge, and Graph attributes](https://www.graphviz.org/doc/info/attrs.html): `shape` is a Node attrbute (`N`, i.e. edges don't have a shape).

Perhaps you are looking for `arrowhead` or `arrowtail` [arrowType](https://www.graphviz.org/doc/info/attrs.html#k:arrowType) or the [`style`](https://www.graphviz.org/doc/info/attrs.html#k:style) attribute?
