### ISSUE TITLE
changing default node style?

### ISSUE THREAD

**Issue by gliptak** [xflr6/graphviz#26]
Following http://stackoverflow.com/a/26553847/304690 I wrote
```
g = graphviz.Graph('G', filename='test.gv')
g.node(shape="box")
```
but it fails to compile with
```
TypeError: node() missing 1 required positional argument: 'name'
```
Is there a different syntax I'm to use for this?

Thanks

**Comment by xflr6** [comment]
As shown in [the docs](http://graphviz.readthedocs.io/en/latest/api.html#graphviz.Graph.node) and the [examples](http://graphviz.readthedocs.io/en/latest/examples.html), the `node()`-method is for creating actual nodes. You are probably looking for the `node_attr` argument (during creation) or attribute (afterwards), which is just a dictionary of key-value pairs with settings:

```python
import graphviz

g = graphviz.Graph('G', filename='test.gv')
g.node_attr.update(shape="box")
g.node('A')
g.node('B')
g.edge('A', 'B')
g.view()
```

**Comment by gliptak** [comment]
@xflr6 Thank you for the details
