### ISSUE TITLE
Make graphviz.backend.FORMATS a public API

### ISSUE THREAD

**Issue by markrwilliams** [xflr6/graphviz#27]
I'd like to write a command line program that uses `graphviz` and presents users with a list of supported image formats for graphs.

If [`graphviz.backend.FORMATS`](https://github.com/xflr6/graphviz/blob/master/graphviz/backend.py#L16-L53) isn't a public API, can it become one?

**Comment by xflr6** [comment]
Sure, done (release pending).

**Comment by markrwilliams** [comment]
Thanks so much!
