### ISSUE TITLE
Possible Dot/Quartz Conflict... Virtualenv on a mac

### ISSUE THREAD

**Issue by Ocean47** [xflr6/graphviz#36]
I am currently running under a virtualenv with python3 and getting hte following error on a mac running sierra os...

pydotplus.graphviz.InvocationException: Program terminated with status: 1. stderr follows: Format: "iris.png" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4 xdot_json

If i type "dot -V" on the command line in the virtualenv i get...
dot - graphviz version 2.40.1 (20161225.0304)

when i type "which dot" i get..
/usr/local/bin/dot

When i install graphviz i use
pip install graphviz

I have read somewhere that there might be a quartz conflict and going to dot version 2.38 fixes the issue.  The problem i have is that I cannot seem to install a different version of dot.  When I install graphiz using..
pip install graphviz==2.38 
I get that that version doesn't exist for graphviz.

Also when i try to install this
pip install pydotplus==2.38 I also get a message saying no such version, but I am unsure how else to try to get dot to change to a different version.  As dot install seemed to install with either graphviz or pydotplus but neither seem to be able to change my version of dot i find in that path above...

Is there something I am missing.  Virtualenv's are new to me, and mac's are not as familiar to me as centos, windows or even old Iris Linux boxes.  So I am a bit new to all this, any help would be greatly appreciated! 

Thanks.

**Comment by xflr6** [comment]
Okay, maybe I can help with some of the confusion: There is Graphviz (http://www.graphviz.org), the graph software written in C and compiled into executables like `dot`. It's latest version is currently 2.38: To update it, take a look at the [download page](http://www.graphviz.org/Download..php) of the project (this does not involve `pip` but usually some platform-specific way of installing, e.g. an installer).

Then there is a number of Python packages that facilitate calling said Graphviz from Python like `pydotplus` you seem to be using (latest version 2.0.2) and this Python package here simply called `graphviz` (latest version 0.6), and also others notably `pygraphviz` and `pydot`. These all are the ones, you can install with `pip` (slogan 'pip installs python packages').

If you have further issues with `pydotplus`, have a look at the corresponding [GitHub page](https://github.com/carlos-jenkins/pydotplus), HTH.
