### ISSUE TITLE
Graph ID must starts with "cluster"

### ISSUE THREAD

**Issue by kakyoism** [xflr6/graphviz#37]
I'm new to Graphviz and this python binding. First of all, this binding works great in general.

For a cluster graph,
I noticed that if the graph ID must starts with the case-sensitive name "cluster", otherwise the output graph will become just a list of strings of all the item labels. All the styles such as shapes will be gone. Examples that work: 

`subg = gv.Digraph('cluster_1')`

`subg = gv.Digraph('cluster1')`

Examples that don't work:

`subg = gv.Digraph('Cluster_1')`
`subg = gv.Digraph('MyID')`

I didn't find cautions regarding this in the DOT language reference, 
so I wonder if this is a feature or a bug on the part of either the graphviz backend or the binding.

Thanks a lot!

**Comment by kakyoism** [comment]
Well, I just found the relevant doc section on Graphviz site. Case closed.

Still, this feature seems hacky. It could have been a dedicated option of the graph definition.

**Comment by xflr6** [comment]
Thanks. This is an upstream issue. Nevertheless, I added a note about this to the documentation in c950e402a0ca28648a882c10406bc4d1d0f36e37
