### ISSUE TITLE
maybe change the linked readthedocs version to 'stable' instead of 'latest'

### ISSUE THREAD

**Issue by awakenting** [xflr6/graphviz#38]
hey,
I installed the package via pip install and then wanted to try out the examples in your documentation. The [fsm.py](http://graphviz.readthedocs.io/en/latest/examples.html#fsm-py) example gave an error and this is when I noticed that I was at the 'latest' branch where the parameter "kw" of the method attr() has now a default value.
So I think it would make sense to link to the 'stable' branch instead so that people don't get confused or notify somehow that if you installed via pip then you should go to 'stable'.
Best,
Andrej

**Comment by xflr6** [comment]
You're right, thanks. Changed the badge and also set the default on readthedocs to stable.

The `g.attr()`-method will gain support for plain attributes like `rank='same'` in the next release (before that, or until then, you need to do that with the `g.body` list, as shown in the [stable docs](https://graphviz.readthedocs.io/en/stable/examples.html#fsm-py)).
