### ISSUE TITLE
render throws error if viewing program has lock on file

### ISSUE THREAD

**Issue by pyeguy** [xflr6/graphviz#45]
when calling `g.render(view=True, cleanup=True)` as i would expect a temp file is created and deleted after the viewing program is closed. However if you leave the viewing program open and it has a lock it will throw the following error:

```python
Error: Could not open "Digraph.gv.pdf" for writing : Permission denied
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~\Desktop\gv_mols.py in <module>()
----> 1 showit(g)

~\Desktop\gv_mols.py in showit(g)
     67
     68 def showit(g):
---> 69         g.render(view=True,cleanup=True)
     70 showit(g)
     71 embed()

C:\Anaconda3\envs\rdkit\lib\site-packages\graphviz\files.py in render(self, filename, directory, view, cleanup)
    169         filepath = self.save(filename, directory)
    170
--> 171         rendered = backend.render(self._engine, self._format, filepath)
    172
    173         if cleanup:

C:\Anaconda3\envs\rdkit\lib\site-packages\graphviz\backend.py in render(engine, format, filepath, quiet)
    122     with open(os.devnull, 'w') as stderr:
    123         try:
--> 124             subprocess.check_call(args, startupinfo=STARTUPINFO, stderr=stderr)
    125         except OSError as e:
    126             if e.errno == errno.ENOENT:

C:\Anaconda3\envs\rdkit\lib\subprocess.py in check_call(*popenargs, **kwargs)
    289         if cmd is None:
    290             cmd = popenargs[0]
--> 291         raise CalledProcessError(retcode, cmd)
    292     return 0
    293

CalledProcessError: Command '['circo', '-Tpdf', '-O', 'Digraph.gv']' returned non-zero exit status 1.
```
which took me an embarrassingly long time to figure out.  

It seems like (particularly with `cleanup=True` ) it should be able to create a unique temp file name to avoid this. I can suggest a PR if you agree.

**Comment by xflr6** [comment]
Thanks. I don't think there is necessarily a connection to `cleanup=True`, which deletes the *source* (`.gv`) file and not the *result* (in this case `.pdf`) file (which would be an extra feature in case that was needed).

The exact behaviour will depend on the plaform and PDF viewer: Linux and Mac OS don't do file system locks and I think under Windows there are also [viewers that will let you overwrite an opened file and just reload](https://superuser.com/questions/599442/pdf-viewer-that-handles-live-updating-of-pdf-doesnt-lock-the-file).

An option would be to block execution after opening the viewer (until it is closed), and I think this was the behaviour at some earlier point that didn't seem too useful.

Yep, using a `tempfile` (or a filename template adding unique parts) to have a unique filename in each invocation of `.render()` would be a nice addition, maybe something along the following lines:

```python
>>> import graphviz
>>> g  = graphviz.Graph(filename=graphviz.tempfile)
>>> g.render()
'c:\\users\\user\\appdata\\local\\temp\\tmpeie6w0.gv.pdf'
>>> g.render()
'c:\\users\\user\\appdata\\local\\temp\\tmpbjs4qi.gv.pdf'
```

**Comment by xflr6** [comment]
Though you could also do something like this (although creating and deleting the `tempfile` via garbage collection to get the unique name is somewhat hackish):

```python
>>> import graphviz, tempfile
>>> g = graphviz.Graph()
>>> g.node('spam')
>>> g.render(filename=tempfile.NamedTemporaryFile(suffix='.gv', delete=True).name)
'C:\\Users\\User\\AppData\\Local\\Temp\\tmpgs6eq8nr.gv.pdf'
>>> g.render(filename=tempfile.NamedTemporaryFile(suffix='.gv', delete=True).name)
'C:\\Users\\User\\AppData\\Local\\Temp\\tmphzbccs13.gv.pdf'
```

**Comment by pyeguy** [comment]
Yes, Windows is really greedy with file locking which can be tiresome. 

I think the `tempfile.mktemp` makes a lot of since if `cleanup=True` since the `cleanup` flag really implies that you're just inspecting the output. 

On things like this i do a lot of iterative, interactive work where inevitably my workflow goes:
create
view
close
tweak
view
close
etc.

and it's pretty easy to substitute a minimize for a close and then get the error produced.

**Comment by xflr6** [comment]
Still, while `cleanup=True` goes together with wanting a different `tempfile` for your use cases, I do not think this is generally true and re-interpreting the flag as currently done in #46 breaks backwards compatibility (see my tentative proposal on a backwards-compatible API above).

For the moment, one could also just add a note with the `tempfile.mktemp` snippet above to the docs.

**Comment by pyeguy** [comment]
yeah sorry, i jumped the gun with that PR. didn't really digest the structure and impetus thereof before diving in. I added a commit that I think addresses the comments you made on #46 but let me know if you think it's going down the wrong road.  I think the tests need to be tweaked to get coverage  get back to 100%

**Comment by xflr6** [comment]
Let's take a step back. I think triggering the `tempfile` usage either warrants a new argument or some special value for `filename` (see above). If you want to continue, maybe start with updating the docstrings of the methods to be modified according to the wanted API (if the new behaviour is hard to explain to the library user, it is probably not ready yet).

**Comment by pyeguy** [comment]
@xflr6  Cool, makes sense. Sorry for the half cocked pr's. I've been tied up with my day job but i'll give this a crack sometime this week if you don't mind leaving the issue and PR open.

**Comment by xflr6** [comment]
I have given this some more thought and I think even a special value for `filename` would break the invariant that `.filepath` points to the actual save location of the DOT source and I am hesitant to change or complicate the API at this point.

Instead, eaa26c04394a26e5b9c47762de6213fa108c1c2e adds some (hopefully helpful) notes summarizing what was said above to the docs (https://graphviz.readthedocs.io/en/latest/manual.html#integration-with-viewers), so I am closing this for now.
