### ISSUE TITLE
node label such as "<> <>" causes syntax error in gv file

### ISSUE THREAD

**Issue by koo5** [xflr6/graphviz#47]
it is thought to be html and does not get quoted
https://github.com/xflr6/graphviz/blob/358371509da30938cfa322a53216f671a369cd20/graphviz/lang.py#L17

**Comment by xflr6** [comment]
Thanks, that was already somewhere in the back of my head. I think, the api needs to be expanded here to support this (e.g. providing  `graphviz.label('<>')`).

In the mean time, a possible workaround would be to add a leading space to the label string.

**Comment by xflr6** [comment]
I.e. like this:
```python
In [1]: import graphviz
   ...: g = graphviz.Graph()
   ...: g.node('spam', label=' <> <>')
   ...: g
Out[1]: 
```
![spam](https://user-images.githubusercontent.com/6342379/32372716-51c93efc-c096-11e7-9f1a-fe19581fda2c.png)

**Comment by koo5** [comment]
thanks
