### ISSUE TITLE
How to save result with Source object

### ISSUE THREAD

**Issue by gkvoelkl** [xflr6/graphviz#48]
Using the Source object like in

```
from graphviz import Source

src = Source('digraph "the holy hand grenade" { rankdir=LR; 1 -> 2 -> 3 -> lob }')
```

how can I save a the result in a file (result.png)?

Bye Gerhard

**Comment by xflr6** [comment]
Please read the documentation:
https://graphviz.readthedocs.io/en/stable/manual.html#using-raw-dot
https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Source.render

**Comment by gkvoelkl** [comment]
works 👍
