### ISSUE TITLE
change styles for existing DOT?

### ISSUE THREAD

**Issue by pathway** [xflr6/graphviz#50]
I wrote a dot_file using networkx.

Then I loaded with graphviz: `dotg = graphviz.Source.from_file(dot_file)`

Now I wish to change global node styles on dotg before rendering, is that possible?

**Comment by xflr6** [comment]
Not really. `graphviz.Source` just represents DOT source as a string, i.e. this libary does not parse (only generates) DOT source code.

If your exported DOT does not really contain style/formatting directives, you might be able to manually insert `attr()` statements such as `node [shape=rarrow]` before your node and edge statements right after the first `{` in your string (or automatically with string replacement or `re`).

If you want to do more complex transformations to your DOT code (e.g. 'do X with all node statements that...'), you might consider a library that (also) parses it such as [pygraphviz](https://pypi.python.org/pypi/pygraphviz) or [pydot](https://pypi.python.org/pypi/pydot).
