### ISSUE TITLE
Support cairo

### ISSUE THREAD

**Issue by PanderMusubi** [xflr6/graphviz#59]
Please support format='svg:cairo' At the moment, this results in:

    ValueError: unknown format: 'svg:cairo'

**Comment by xflr6** [comment]
Thanks. Can you check if the [change in the format branch](https://github.com/xflr6/graphviz/compare/format) satisfies your use case?

**Comment by xflr6** [comment]
Added in 2f16b26dcce564d249134de09253e593a5baeeed.

**Comment by PanderMusubi** [comment]
Thanks. Looking forward to seeing this next release in PyPI.
