### ISSUE TITLE
syntax error in centos6.7

### ISSUE THREAD

**Issue by liuhetongzi** [xflr6/graphviz#61]
windows: dot - graphviz version 2.38.0 (20140413.2041)    graphviz (0.10.1)
                  It return the correct result.
centos6.7: dot - graphviz version 2.26.0 (20091210.2329)   graphviz (0.10.1)
                It cause the syntax error.
The code is the same.I use python 3.5.Is it a bug? Thank you.

My code:

from graphviz import Digraph
import os
#os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'
dot = Digraph(comment='The Test Table',format='png')
dot.attr(rankdir='LR')
dot.node('A', u'zeus \n信息资源申请',fontname="SimSun",color='green', style='filled')
dot.node('B', u'jason \n部门负责人审批 ',fontname="SimSun",shape='diamond',color='lightblue2', style='filled')
dot.node('C', u'alex \n中心负责人审批',fontname="SimSun",shape='diamond',color='lightblue2', style='filled')
dot.node('D', u'zeus \n申请人确认',fontname="SimSun",shape='diamond',color='lightblue2', style='filled')
dot.node('E', u'归档',fontname="SimSun",color='green', style='filled')
dot.edges(['AB', 'BC','CD','DE'])
dot.edge('B', 'A', u'驳回',fontname="SimSun")
dot.edge('C', 'A', u'驳回',fontname="SimSun")
print(dot.source)
dot.render('test-output/test-table.gv', view=False)
#view=True 自动打开
         
In windows is ok,but in centos6.7 it cause error.The error is:

// The Test Table
digraph {
	rankdir=LR
	A [label="zeus 
信息资源申请" color=green fontname=SimSun style=filled]
	B [label="jason 
部门负责人审批 " color=lightblue2 fontname=SimSun shape=diamond style=filled]
	C [label="alex 
中心负责人审批" color=lightblue2 fontname=SimSun shape=diamond style=filled]
	D [label="zeus 
申请人确认" color=lightblue2 fontname=SimSun shape=diamond style=filled]
	E [label="归档" color=green fontname=SimSun style=filled]
	A -> B
	B -> C
	C -> D
	D -> E
	B -> A [label="驳回" fontname=SimSun]
	C -> A [label="驳回" fontname=SimSun]
}
Warning: test-output/test-table.gv:4: string ran past end of line
Warning: test-output/test-table.gv:5: string ran past end of line
Error: test-output/test-table.gv:6: syntax error near line 6
context: 	B >>>  [ <<< label="jason 
Warning: test-output/test-table.gv:6: string ran past end of line
Warning: test-output/test-table.gv:7: string ran past end of line
Warning: test-output/test-table.gv:8: string ran past end of line
Warning: test-output/test-table.gv:9: string ran past end of line
Warning: test-output/test-table.gv:10: string ran past end of line
Warning: test-output/test-table.gv:11: string ran past end of line
Traceback (most recent call last):
  File "test_graphviz.py", line 46, in <module>
    dot.render('test-output/test-table.gv', view=False)
  File "/opt/py35env/lib/python3.5/site-packages/graphviz/files.py", line 188, in render
    rendered = backend.render(self._engine, format, filepath, renderer, formatter)
  File "/opt/py35env/lib/python3.5/site-packages/graphviz/backend.py", line 183, in render
    run(cmd, capture_output=True, check=True, quiet=quiet)
  File "/opt/py35env/lib/python3.5/site-packages/graphviz/backend.py", line 159, in run
    raise CalledProcessError(proc.returncode, cmd, output=out, stderr=err)
subprocess.CalledProcessError: Command '['dot', '-Tpng', '-O', 'test-output/test-table.gv']' returned non-zero exit status 1

what's wrong with me? Please help me .Thanks..

**Comment by xflr6** [comment]
Please refer to Graphviz (https://graphviz.gitlab.io) for the font problem.
Closing (upstream issue unrelated to this library).
