### ISSUE TITLE
Bug with nosetests and --with-xunit

### ISSUE THREAD

**Issue by JeremyMarshall** [xflr6/graphviz#62]
Install nosetests and the [with-xunit](https://nose.readthedocs.io/en/latest/plugins/xunit.html) support

then run the following test with `nosetests --with-xunit`

```python
from graphviz import Digraph, Graph

def test_broken():
    dot = Digraph(name='name', format='plain', graph_attr={'rankdir':'LR'})
    dot.attr(style='filled')
    dot.node_attr.update(style='filled', color='white')

    dot.node('1','1', {'color': 'not-a-colour'})
    dot.node('2','2', {'color': 'not-a-colour'})
    dot.edge('1','2', None, {'color': 'not-a-colour'})

    dot.render('test', view=False)
```

and it fails with
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/marsje/src/github/graphviz-error/test_gv.py", line 12, in test_broken
    dot.render('test', view=False)
  File "/usr/local/lib/python3.7/site-packages/graphviz/files.py", line 176, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/usr/local/lib/python3.7/site-packages/graphviz/backend.py", line 142, in render
    run(cmd, capture_output=True, check=True, quiet=quiet)
  File "/usr/local/lib/python3.7/site-packages/graphviz/backend.py", line 120, in run
    stderr_write_bytes(err, flush=True)
  File "/usr/local/lib/python3.7/site-packages/graphviz/_compat.py", line 41, in stderr_write_bytes
    encoding = sys.stderr.encoding or sys.getdefaultencoding()
AttributeError: 'Tee' object has no attribute 'encoding'
```
Seems like its trying to do something with stderr (as it is complaining about a colour not being a colour) but then failing.

I came across this using mock to mock out my colour selection and got round it by mocking a real colour, but then other stderr messages can break it to, I would think

Python 3.x on mac

**Comment by xflr6** [comment]
Can you check if the following test breaks in your setup:
```python
import sys

def test_broken():
    assert hasattr(sys, 'encoding')
```
If so, I think this might be a `nose`or `xunit` issue, can you try to report there?

`CalledProcessError` and `stderr` output come from the failing rendering process due to the invalid colours, right?

We could consider changing the last traceback code line into the following (can you try if that suffices?):
```python
encoding = getattr(sys.stderr, 'encoding', None) or sys.getdefaultencoding()
```

**Comment by xflr6** [comment]
BTW, the third `.node()` argument and the fourth `.edge()` argument (`_attributes`) are not official API (might be removed in `1.0`, but currently no incentive).

**Comment by JeremyMarshall** [comment]
It looks like a problem in the xunit part

```
FAIL: test_gv.test_broken2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/marsje/src/github/graphviz-error/test_gv.py", line 16, in test_broken2
    assert hasattr(sys.stderr, 'encoding')
AssertionError
```
but only if I use `--with-xunit` otherwise it works- which is what my original test did

**Comment by JeremyMarshall** [comment]
Its a pity about the `_attributes` I tend to pass the parameters back as a tuple then `dot.node(*tuple)` them so I can decouple the generation from the config for testing

**Comment by xflr6** [comment]
Okay, will close for now then.

Maybe I am missing something, but if `tuple_` is something like
`('name', 'label', {'color': 'blue'})`
can't you just do `dot.node(*tuple_[:-1], **tuple_[-1])`?
