### ISSUE TITLE
How do you add dot executables to system PATH in mac?

### ISSUE THREAD

**Issue by kylefoley76** [xflr6/graphviz#63]
When I run graphviz I get the following error

graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'test-output/aoc.gv.pdf'], make sure the Graphviz executables are on your systems' PATH

I don't know what the graphviz executables are.  In any case, my best guess is that I have to add the path of the module that uses graphviz or I have to add the graphviz module to my .bash_profile.  Currently, my bash_profile has this line:

PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}

So I tried adding the path of where the module that uses Graphviz is located which is

/Users/kylefoley/PycharmProjects/inference_engine2/inference2/proofs/other/use_graphviz.py

Plus the graphviz module itself which is:

/library/frameworks/python.framework/versions/3.6/lib/python3.6/site-packages/graphviz/

Making the final product to be:

PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}:/Users/kylefoley/PycharmProjects/inference_engine2/inference2/proofs/other/use_graphviz.py:/library/frameworks/python.framework/versions/3.6/lib/python3.6/site-packages/graphviz/"

But that did not work.  I need to know what string I have to add to the PATH.

**Comment by xflr6** [comment]
See https://graphviz.readthedocs.io/en/stable/manual.html#installation: the directory that need to be added to the PATH is the one that contains the binaries from Graphviz (https://www.graphviz.org/download/) such as `dot`.

**Comment by kylefoley76** [comment]
Hi xflr6, thanks for taking the time to help me out but I don't understand what you mean.  The only directory that I know of that might contain binaries from Graphviz is library/frameworks/python.framework/versions/3.6/lib/python3.6/site-packages/graphviz which contains dot.py and files.py among others.  I tried adding that directory to my path as well as library/frameworks/python.framework/versions/3.6/lib/python3.6/site-packages/graphviz/dot.py but that did not work.  When I clicked on https://www.graphviz.org/download/ I didn't see anything which would obviously help me with my problem.  Any help would be most appreciated.

**Comment by xflr6** [comment]
Hi Kyle. I suspect there is some confusion: This Python library `graphiz` provides a Python API for Graphviz (written in C, https://gitlab.com/graphviz/graphviz, https://www.graphviz.org/download/), which must be installed separately. The latter has a `bin/` subdirectory, which contains binary executable files such as `dot`, `neato`, etc. (which is a different thing than the Python script (text) files such as `dot.py` that come with this library). You need to ensure that on the command line e.g. `dot -V` prints the version of your Graphviz installation, which might require adding its `bin/`directory to your PATH.

**Comment by kylefoley76** [comment]
Thanks, I solved the problem.
