### ISSUE TITLE
How to build graph like a set of horizontal levels of nodes?

### ISSUE THREAD

**Issue by sergorl** [xflr6/graphviz#64]
I want to build graph like [that](https://ibb.co/WknTVK6). How can I do it?

**Comment by xflr6** [comment]
Does [this](https://stackoverflow.com/questions/25734244/how-do-i-place-nodes-on-the-same-level-in-dot) help?

```python
import graphviz

d = graphviz.Digraph()

with d.subgraph() as s:
    s.attr(rank='same')
    s.node('A')
    s.node('X')

with d.subgraph() as s:
    s.node('C')

with d.subgraph() as s:
    s.attr(rank='same')
    s.node('B')
    s.node('D')
    s.node('Y')

d.edges(['AB', 'AC', 'CD', 'XY'])
d
```

![d](https://user-images.githubusercontent.com/6342379/54394323-d6963c00-46ac-11e9-9c98-4773206e4c4f.png)

**Comment by sergorl** [comment]
No, it doesn't. What's need:

Level 0: node 1, node 2, node 3
Level 1: node 4, node 5
Level 2: node 6, node 7, node 8
Level 3: node 9, node 10

If I'll add an edge between two any nodes, the structure of levels shouldn't change- it's need to add only edge - black line, without any permutations of nodes from one level to another.

Here is my contra-example, which doesn't work properly similarly the structure description above
```python
import graphviz

d = graphviz.Digraph(format='png')

#Level 0
with d.subgraph() as s:
    s.attr(rank='same')
    s.node('1')
    s.node('2')
    s.node('3')

#Level 1
with d.subgraph() as s:
    s.node('4')
    s.node('5')

#Level 2
with d.subgraph() as s:
    s.attr(rank='same')
    s.node('6')
    s.node('7')
    s.node('8')

#Level 3
with d.subgraph() as s:
    s.attr(rank='same')
    s.node('9')
    s.node('10')

d.edges(['14', '47', '38', '25', '39'])
d.view()
```

When I run this code I see that "Level 3" goes to "Level 1" and it breaks my logic of graph construction.

**Comment by xflr6** [comment]
I think you might need invisible edges, please refer to https://www.graphviz.org/contact/ for support on graph layout  questions (maybe sites lieke stackoverflow can also help).
