### ISSUE TITLE
How to provide direct path to engine executables?

### ISSUE THREAD

**Issue by dinya** [xflr6/graphviz#65]
Currently I should modify my PATH env 

```python
import os
os.environ["PATH"] += r";C:\opt\miniconda3\Library\bin\graphviz"
```
for graphviz from conda repo (https://anaconda.org/anaconda/graphviz).

How to provide direct path to graphviz executables without monkey-patching of the library?

**Comment by xflr6** [comment]
Hi, here is how you [set your PATH under Windows](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/), not sure if that helps within the *conda environment.

There is also a community-driven anaconda version/distribution of this package [python-graphviz](https://anaconda.org/conda-forge/python-graphviz), which AFAIU should install both `python-graphviz` (i.e. an adapted version of this package) and [graphviz](https://anaconda.org/anaconda/graphviz) (i.e. the anaconda version/distribution of [Graphviz](http://www.graphviz.org)), and set-up eveything, so the executables like `dot` are usable in the *conda environment. See also [python-graphviz-feedstock](https://github.com/conda-forge/python-graphviz-feedstock) and [conda-forge/graphviz-feedstock](https://github.com/conda-forge/graphviz-feedstock/).

**Comment by dinya** [comment]
@xflr6 

According to you recomendations I installed packages https://github.com/conda-forge/python-graphviz-feedstock (python-graphviz-0.10) and https://github.com/conda-forge/graphviz-feedstock/ (graphviz-2.38.0):

```bash
conda config --add channels conda-forge
conda install graphviz
conda install python-graphviz
```

But without ``os.environ["PATH"] += r";<CONDA_PATH>\Library\bin\graphviz`` ``python-graphviz`` still raises

```python
ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH
```

Why so?

``conda install graphviz`` installs GraphViz in ``<CONDA_PATH>\Library\bin\graphviz`` with DOT executables in:

* ``<CONDA_PATH>\Library\bin\graphviz\dot.exe`` (**not** in ``PATH``)
* ``<CONDA_PATH>\Library\bin\dot.bat`` (in ``PATH``, I think conda team emulates *nix simlink in such way).

``dot.bat`` contains:

```batch
@echo off 
%~dp0.\graphviz\dot.exe %* 
```

But ``python-graphviz`` doesn't use ``dot.bat`` (wich in ``PATH``), and needs ``dot.exe`` in ``PATH`` (i.e. needs ``<CONDA_PATH>\Library\bin\graphviz`` in ``PATH``).

I don't understand this behavior because ".bat" files should be executable for windows shells (see ``PATHEXT``).

That's why I propose to add in ``python-graphviz`` constant for graphviz engines executables path. For example to be compatible with current behaviour something like:

* ``GRAPHVIZ_PATH = ""``
* ``DOT_EXE = "dot"``
* ...

So ``os.path.join(GRAPHVIZ_PATH, DOT_EXE)`` returns ``"dot"`` (current behaviour).


-----

My current "hacky" way for conda's ``graphviz``+``python-graphviz`` pair is :

```python
import graphviz.backend

DOT = "dot"

def test_dot(dot_name):
    s = Source("graph {}", engine=dot_name)
    _ = s.pipe(format='svg').decode(s._encoding)
    
try:
    test_dot(DOT)
except graphviz.backend.ExecutableNotFound:
    try:
        DOT = "dot.bat"
        graphviz.backend.ENGINES.add(DOT)
        test_dot(DOT)
    except graphviz.backend.ExecutableNotFound:
        raise

from graphviz import Source
Source(source, engine=DOT)
```

**Comment by xflr6** [comment]
Thanks for the details. Sorry to hear Anaconda `python-graphviz` did not work either. I usually just install Graphviz from graphviz.org, add it to my PATH, and `pip install graphviz` on my normal system Python (both under Linux and Windows). As [python-graphviz-feedstock](https://github.com/conda-forge/python-graphviz-feedstock) is not maintained by me, I can only try to help with it as good as I can.

Can you maybe open an issue for Anaconda `python-graphviz` (AFAIU, they [used to have a patch](https://github.com/conda-forge/python-graphviz-feedstock/blob/d83128c4d98ac54ef346b2b529a7cb0dd59e66b4/recipe/windows-bat.patch) so that the Windows version uses their `dot.bat` wrapper script, which they neeed to workaround library load issues in the Anaconda Windows-distribution of Graphviz, but maybe it works differently now)?
