### ISSUE TITLE
Add support for running in MyBinder

### ISSUE THREAD

**Issue by psychemedia** [xflr6/graphviz#66]
To make it easier for potential users to demo this package, the repo can be configured so that that a pre-configured Jupyter notebook server can be launched from it and the example notebook(s) run directly using [MyBinder](https://mybinder.org/).

Changes required:

- add a `binder` directory;
- to `binder/apt.txt` add the `graphviz` requirement;
- to `binder/requirements.txt` add the `.` requirement to install the package from the repo root.

**Comment by xflr6** [comment]
Hi, as I don't use MyBinder myself I am not sure about the benefits: would this be more for developing and testing this package or for using it (maybe there is a better way to fire up a notebook with some pre-installed dependencies, i.e. without requiring a change in the repo of the dependency)? Maybe you have pointer so some packages that already do this?

**Comment by psychemedia** [comment]
One advantage is that someone can try the package without having to install anything themselves. Another is that it's a quick way of testing (as a user) whether the package installs and runs correctly. A third is that it gets you to list any package dependencies in an obvious place so that MyBinder can build an environment containing those dependencies for you.

For example, using this branched fork: https://github.com/ouseful-PR/graphviz/tree/binderise

you can try out the demo notebook using MyBinder: https://mybinder.org/v2/gh/ouseful-PR/graphviz/binderise?filepath=examples%2Fnotebook.ipynb

There is a set of "offical" Binderised example repos here: https://github.com/binder-examples/

Repos that define Python packages with a `setup.py` file at the top of the repo will automatically install the package if the repo is run via MyBinder. If there are particular sorts of requirements files listed at the top of the repo, they will automatically be used to build an environment too. This is great for users: I can try out your package via a browser without having to install anything on my machine. And if it doesn't install or doesn't work, I know it's not my fault...!

To make it easier for people to run a repo via MyBinder, you can add a *launch Binder* button. For example, click the buttons in the README of these repos:

- https://github.com/QuantStack/ipysheet
- https://github.com/jakevdp/PythonDataScienceHandbook
- https://github.com/jupyter-widgets/ipyleaflet

Note that sometimes containers may be slow to launch, depending on load. But you can also run things locally (if you have docker installed) using [`repo2docker`](https://repo2docker.readthedocs.io/en/latest/) which will build a docker image and launch a container from it containing a Jupyter notebook server and an environment customised according to the recognised requirements in your repository.

**Comment by betatim** [comment]
> (maybe there is a better way to fire up a notebook with some pre-installed dependencies, i.e. without requiring a change in the repo of the dependency)?

One thing you can do is create a repo like https://github.com/ines/spacy-io-binder which is used by https://spacy.io/usage/linguistic-features to power their interactive code insets in the documentation. This is an example of having a separate repo to setup the environment. There are a few other people who do this but one drawback is that you need to make some home cooked thing to pull in the demo/example material from the main repository afterwards.

https://twitter.com/BokehPlots/status/1116783897604321280 is another example where they have a repo that launches on mybinder.org but the actual package is in a different repo. They solved the sync'ing problem by having all their demos in the repo that launches on mybinder.org

**Comment by cod3licious** [comment]
Hey! I'm building a Python tutorial that includes the visualization of a scikit-learn decision tree with graphviz. For easier access, I wanted to provide the tutorial via mybinder.org. Putting graphviz as a dependency worked for the installation and I can execute
```python
dot_data = tree.export_graphviz(clf, out_file=None, feature_names=feature_cols, filled=True, class_names=np.array(clf.classes_, dtype=str)) 
graph = graphviz.Source(dot_data)
```
without any problems. But then when trying to render the graph in the notebook (by calling `graph`) I get the following error:
```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.6/site-packages/graphviz/backend.py in run(cmd, input, capture_output, check, quiet, **kwargs)
    152     try:
--> 153         proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
    154     except OSError as e:

/srv/conda/envs/notebook/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:

/srv/conda/envs/notebook/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1343                             err_msg += ': ' + repr(err_filename)
-> 1344                     raise child_exception_type(errno_num, err_msg, err_filename)
   1345                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

ExecutableNotFound                        Traceback (most recent call last)
<ipython-input-52-80c7345b5678> in <module>
      3 graph = graphviz.Source(dot_data)
      4 # save tree as decision_tree.pdf
----> 5 graph.render("decision_tree", view=False)
      6 #graph

/srv/conda/envs/notebook/lib/python3.6/site-packages/graphviz/files.py in render(self, filename, directory, view, cleanup, format, renderer, formatter, quiet)
    199         rendered = backend.render(self._engine, format, filepath,
    200                                   renderer=renderer, formatter=formatter,
--> 201                                   quiet=quiet)
    202 
    203         if cleanup:

/srv/conda/envs/notebook/lib/python3.6/site-packages/graphviz/backend.py in render(engine, format, filepath, renderer, formatter, quiet)
    198     else:
    199         cwd = None
--> 200     run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
    201     return rendered
    202 

/srv/conda/envs/notebook/lib/python3.6/site-packages/graphviz/backend.py in run(cmd, input, capture_output, check, quiet, **kwargs)
    154     except OSError as e:
    155         if e.errno == errno.ENOENT:
--> 156             raise ExecutableNotFound(cmd)
    157         else:
    158             raise

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'decision_tree'], make sure the Graphviz executables are on your systems' PATH
```
Can this be solved by making the repo binder-friendly?

**Comment by psychemedia** [comment]
@cod3licious In your own Binder repo, you need to add `graphviz` to an `apt.txt` or conda `environment.yml` file; Binder will then install it for you.

**Comment by cod3licious** [comment]
@psychemedia I had added it to a requirements.txt file and I think it was installed without a problem since I could import it and execute the code that generated the graph itself. Only when trying to actually *render* the graph I got the error message since it seems to be missing `dot`...

**Comment by psychemedia** [comment]
@cod3licious You need both dependencies - the `graphviz` Python package installed via `requirements.txt` provides a wrapper to the commandline Graphivz tool, which is installed via `apt.txt` and is the thing that actually does the graph rendering.

**Comment by cod3licious** [comment]
perfect, it worked - thanks so much!

**Comment by hexagonrecursion** [comment]
Binder is a great tool for trying things out without having to install them. It is the best mechanism I know of for delivering tutorials and examples. Making graphviz examples available via binder will be a big improvement.
