### ISSUE TITLE
Cannot extend existing class by inherintance when using subgraph

### ISSUE THREAD

**Issue by yegle** [xflr6/graphviz#7]
`Graph.subgraph` and `Digraph.subgraph` have a very strict checking for class type which makes it impossible to extend existing class by inheritance.

For example, I have the following class definition:

```
class ClusterGraph(Graph):
    def __init__(self, name):
        Graph.__init__("cluster_"+name)

g1 = Graph()
g2 = ClusterGraph()
g1.subgraph(g2) # will fail because of the strict type checking.
```

**Comment by dizcza** [comment]
I have the same error. It's very sad that the users cannot subclass the graph.
```python
import graphviz

class GraphArea(graphviz.Digraph):
    def __init__(self, **kwargs):
        super().__init__(name='graph', format='svg',
                         graph_attr=dict(rankdir='LR'),
                         node_attr=dict(shape='box'))
        with self.subgraph(name="cluster_0") as c:
            print(c)


GraphArea()
```

Recursion error.

**Comment by xflr6** [comment]
Thanks. AFAICT subclassing works as intended. I understand the use case is to define defaults, e.g.:

```python
In [1]: import graphviz
   ...: 
   ...: class GraphArea(graphviz.Digraph):
   ...:     def __init__(self,
   ...:                  name='graph',
   ...:                  format='svg',
   ...:                  graph_attr={'rankdir': 'LR'},
   ...:                  node_attr={'shape': 'box'},
   ...:                  **kwargs):
   ...:         super().__init__(name=name,
   ...:                          format=format,
   ...:                          graph_attr=graph_attr,
   ...:                          node_attr=node_attr,
   ...:                          **kwargs)
   ...:                          
   ...:         
   ...: 
   ...: g = GraphArea()
   ...: with g.subgraph(name="cluster_0") as s:
   ...:     s.node('spam')
   ...: print(g)
digraph "graph" {
	graph [rankdir=LR]
	node [shape=box]
	subgraph cluster_0 {
		spam
	}
}
```

Note that in the code you have given `GraphArea` silently ignores any given arguments (not passing `kwargs`).

If setting defaults is all that is needed, one can do it much simpler with `functools.partial`:
```python
import functools

GraphArea = functools.partial(graphviz.Digraph,
                              name='graph',
                              format='svg',
                              graph_attr={'rankdir': 'LR'},
                              node_attr={'shape': 'box'})
```

It understand you might want to precreate nodes/edges/subgraphs in `__init__`. Not sure if that makes sense (maybe a (factory) function would be much simpler), but that does work (with subgraphs created by that class also containing the precreated content): You are getting `RecursionError` from adding a subgraph in the initializer, which means that this subgraph again creates a subgraph and so on recursively, so I think the error is correct here.
