### ISSUE TITLE
Windows 10 install fails

### ISSUE THREAD

**Issue by fraseg** [xflr6/graphviz#73]
I amended the setup.py script to include hard paths for include and lib directories for graphviz but get the following problems. I have spent two days trying to resolve it and I find that this is an ongoing issue for some years now. If there is a solution please can you amend the README with details of an install process that works on windows 10?

here is my output
`C:\Users\44753\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\dist.py:472: UserWarning: Normalizing '1.6.dev' to '1.6.dev0'
  normalized_version,
running install
include_dirs=None
library_dirs=None
running build
running build_py
running egg_info
writing pygraphviz.egg-info\PKG-INFO
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing top-level names to pygraphviz.egg-info\top_level.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.png' under directory 'doc'
warning: no files found matching '*.html' under directory 'doc'
warning: no files found matching '*.txt' under directory 'doc'
warning: no files found matching '*.css' under directory 'doc'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-IC:\Program Files (x86)\Graphviz2.38\include" -IC:\Users\44753\AppData\Local\Programs\Python\Python37\include -IC:\Users\44753\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.7\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(3328): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
pygraphviz/graphviz_wrap.c(3346): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
pygraphviz/graphviz_wrap.c(3354): warning C4047: 'return': 'int' differs in levels of indirection from 'Agsym_t *'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files (x86)\Graphviz2.38\lib\debug\lib" /LIBPATH:C:\Users\44753\AppData\Local\Programs\Python\Python37\libs /LIBPATH:C:\Users\44753\AppData\Local\Programs\Python\Python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" cdt.lib cgraph.lib /EXPORT:PyInit__graphviz build\temp.win-amd64-3.7\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win-amd64-3.7\pygraphviz\_graphviz.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\pygraphviz\_graphviz.cp37-win_amd64.lib
   Creating library build\temp.win-amd64-3.7\Release\pygraphviz\_graphviz.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\pygraphviz\_graphviz.cp37-win_amd64.exp
graphviz_wrap.obj : error LNK2001: unresolved external symbol agwrite
graphviz_wrap.obj : error LNK2001: unresolved external symbol agisdirected
graphviz_wrap.obj : error LNK2001: unresolved external symbol agopen
graphviz_wrap.obj : error LNK2001: unresolved external symbol agraphof
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtin
graphviz_wrap.obj : error LNK2001: unresolved external symbol aglstnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agedge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agsubedge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agisundirected
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agidnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtsubg
graphviz_wrap.obj : error LNK2001: unresolved external symbol agisstrict
graphviz_wrap.obj : error LNK2001: unresolved external symbol agattrsym
graphviz_wrap.obj : error LNK2001: unresolved external symbol agfstin
graphviz_wrap.obj : error LNK2001: unresolved external symbol agattr
graphviz_wrap.obj : error LNK2001: unresolved external symbol agstrdup_html
graphviz_wrap.obj : error LNK2001: unresolved external symbol Agdirected
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnameof
graphviz_wrap.obj : error LNK2001: unresolved external symbol agfstnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agget
graphviz_wrap.obj : error LNK2001: unresolved external symbol agdegree
graphviz_wrap.obj : error LNK2001: unresolved external symbol agfstedge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agdelsubg
graphviz_wrap.obj : error LNK2001: unresolved external symbol agdelnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtattr
graphviz_wrap.obj : error LNK2001: unresolved external symbol agread
graphviz_wrap.obj : error LNK2001: unresolved external symbol agparent
graphviz_wrap.obj : error LNK2001: unresolved external symbol agxset
graphviz_wrap.obj : error LNK2001: unresolved external symbol agclose
graphviz_wrap.obj : error LNK2001: unresolved external symbol agidedge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agroot
graphviz_wrap.obj : error LNK2001: unresolved external symbol agfstsubg
graphviz_wrap.obj : error LNK2001: unresolved external symbol agdeledge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnnodes
graphviz_wrap.obj : error LNK2001: unresolved external symbol Agundirected
graphviz_wrap.obj : error LNK2001: unresolved external symbol agxget
graphviz_wrap.obj : error LNK2001: unresolved external symbol agsubnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtedge
graphviz_wrap.obj : error LNK2001: unresolved external symbol agsubg
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnedges
graphviz_wrap.obj : error LNK2001: unresolved external symbol agset
graphviz_wrap.obj : error LNK2001: unresolved external symbol agfstout
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol agsafeset
graphviz_wrap.obj : error LNK2001: unresolved external symbol agprvnode
graphviz_wrap.obj : error LNK2001: unresolved external symbol Agstrictundirected
graphviz_wrap.obj : error LNK2001: unresolved external symbol PyIOBase_Type
graphviz_wrap.obj : error LNK2001: unresolved external symbol agnxtout
graphviz_wrap.obj : error LNK2001: unresolved external symbol Agstrictdirected
build\lib.win-amd64-3.7\pygraphviz\_graphviz.cp37-win_amd64.pyd : fatal error LNK1120: 50 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120`

Thanks in advance

Gus

**Comment by xflr6** [comment]
Sorry to hear that. Looks like you are trying to install [pygraphviz](https://pypi.org/project/pygraphviz/) (if they don't provide  windows-specific wheels, this might require a compiler, which is a bit tricky so set-up on Windows), see https://github.com/pygraphviz/pygraphviz for support.

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pygraphviz seems to only provide Python 2.

If all you need to do is create graphs, you can also try this (less poweful) package,  which is pure-python and thereby does not require a compiler (one of the reason I originally created it).
