### ISSUE TITLE
Can't compare Digraphs for equality

### ISSUE THREAD

**Issue by dms-cat** [xflr6/graphviz#74]
To reproduce:

```python
>>> from graphviz import Digraph
>>> Digraph() == Digraph()
False
```

Ideally two `Digraph`s representing the same graph should be equal.

Workaround:

```python
>>> Digraph().source == Digraph().source
True
```

**Comment by xflr6** [comment]
Thanks. I think equivalence checking should only be implemented if its semantics is obvious (so its unlikely that it needs to be changed at some point). To 'represent the same graph' is not necessarily the same as having the same source and so I think your second example is actually much clearer than the first one, WDYT?

For illustration:

```python
import graphviz

d = graphviz.Digraph()
d.node('hello')
d.node('world')
d.edge('hello', 'world')

d
```
![screen](https://user-images.githubusercontent.com/6342379/60083290-c2df8480-9735-11e9-9ecd-828e0946a047.png)

```python
d_ = graphviz.Digraph()
d_.edge('hello', 'world')

d_
```
![screen](https://user-images.githubusercontent.com/6342379/60083355-dee32600-9735-11e9-8443-6c99a324bcdc.png)

```python
assert d.source != d_.source
```

**Comment by dms-cat** [comment]
You're right. After looking at the code it looks like there's no normalization to make sure source equality ↔ graph properties equality, so source equality is probably the best we can do for now.

**Comment by xflr6** [comment]
Thanks. It might work with [pygraphviz](https://pygraphviz.github.io/) (at least I think they build up the graph  structure in memory first).
