### ISSUE TITLE
Convert obj from Source to Digraph or add attr to obj from Source

### ISSUE THREAD

**Issue by hassanfa** [xflr6/graphviz#76]
Hi,

I have a `graph_obj` from Source that I'm trying to add a label to it.

```
graph_obj = graphviz.Source(graph_dot, 
                            filename=graph_dot_name,
                            format="pdf",
                            engine="dot")
```

I was wondering if there is a way to use something like this to add labels to my graph:

```
graph_obj.attr('graph',label='my_label')
```

**Comment by xflr6** [comment]
Hi, not with this library (`Source` objects [dont have modification-methods](https://graphviz.readthedocs.io/en/stable/manual.html#using-raw-dot)). You might want to take a closer look at `pygraphviz` or `pydot` ([mentioned here](https://graphviz.readthedocs.io/en/stable/index.html#see-also)). IIRC both allow to parse DOT source code into a mutable data structure (this library is ony for programmatic generaton and rendering).

**Comment by ray-ronnaret** [comment]
https://stackoverflow.com/a/67143816/14076061
