### ISSUE TITLE
Full list of supported output format?

### ISSUE THREAD

**Issue by laike9m** [xflr6/graphviz#77]
I cannot seem to find a full list of supported output format on the [API doc](https://graphviz.readthedocs.io/en/stable/api.html#graph). Is everything on this [list](https://www.graphviz.org/doc/info/output.html) supported? Or only a subset?

**Comment by xflr6** [comment]
Hi, the set of output formats is avaliable as [`graphviz.FORMATS` ](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.FORMATS) ([current source](https://github.com/xflr6/graphviz/blob/fa17c33e0ae8d3ec6c6d9214009ecc75dab3e433/graphviz/backend.py#L23-L61)).
