### ISSUE TITLE
Got unintelligible text when using  Chinese characters.

### ISSUE THREAD

**Issue by sazima** [xflr6/graphviz#78]
```python
from graphviz import Digraph

dot = Digraph(comment='The Test Table', format="png")
dot.node('A', '开始')
dot.node('B', 'it审核', shape='box')
dot.node('C', '结束')
dot.edges(['AC', 'BA'])
dot.edge('B', 'C', '通过')
dot.edge('A', 'B', '提交')
dot.render(filename='test')
```
and get the png picture:

![test.png](https://i.loli.net/2019/07/31/5d41719c5dda966522.png)

**Comment by xflr6** [comment]
Hi, I think this is an issue with selecting the right font (`dot.graph_attr['fontname']`, I think) on your system (what you see are replacement characters for missing glyphs IIUC). I get the same  result when rendering to png or pdf. But with SVG, the graph is displayed correctly (AFAICT) in my SVG viewer. Same in the qtconsole:

![screen](https://user-images.githubusercontent.com/6342379/62233873-c4057080-b3c9-11e9-9c70-516861fe3e30.png)

If the rendering is broken in some way (I suspect not), then this would go to https://gitlab.com/graphviz/graphviz/issues (the Python wrapper here seems to work as intended).

**Comment by sazima** [comment]
@xflr6 thanks! svg works for me .
