### ISSUE TITLE
"Cannot allocate memory" in call to render

### ISSUE THREAD

**Issue by ifed-ucsd** [xflr6/graphviz#79]
I am consistently hitting the following error when calling the render function multiple times:

  File "/usr/local/lib/python3.6/dist-packages/graphviz/files.py", line 201, in render
    quiet=quiet)
  File "/usr/local/lib/python3.6/dist-packages/graphviz/backend.py", line 200, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/usr/local/lib/python3.6/dist-packages/graphviz/backend.py", line 153, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
[1]+  Done                    rm -rf test/lenet_nas/*

**Comment by xflr6** [comment]
Are you maybe rendering a speficically large or complex graph? Can you run `free` on your system (out of memory)? Are you running it in the background (`<cmd> &`)?

I just ran `render()` on an example file >1000 times and the size of  the process did not change,  same for calling the ` .render()`-method on  a `Digraph` object that often.

**Comment by ifed-ucsd** [comment]
I'm using the python graphviz digraph class. I don't see a `free` method anywhere? The graph is not that large (~10 nodes). I tried calling `clear` on the digraph object, but that did not help.

**Comment by xflr6** [comment]
Sorry, I meant  running [`free` on the command line](https://askubuntu.com/questions/845233/running-any-command-returns-cannot-allocate-memory-on-ubuntu-server) on your system.

**Comment by xflr6** [comment]
Closing as this seems to be unrelated to this library.
