### ISSUE TITLE
Nested subgraphs?

### ISSUE THREAD

**Issue by bdejong** [xflr6/graphviz#84]
Hi,

am I seeing this correctly that a subgraph can not contain another subgraph?

because... graphviz does allow one to do this.

in these bindings I get:

```
AttributeError: 'SubgraphContext' object has no attribute 'subgraph'
```

**Comment by bdejong** [comment]
Simpelest example that doesn't seem to work:

```python
    a = Graph(name='A')
    a.edge('1', '2')

    b = Graph(name='cluster_B')
    b.edge('3', '4')

    c = Graph(name='cluster_C')
    c.edge('5', '6')

    a.subgraph(b)
    b.subgraph(c)

    a.view()
```

This shows only 1/2/3/4 but not 5/6

**Comment by xflr6** [comment]
Hi, note that there is an [example nestes subgraphs](https://graphviz.readthedocs.io/en/stable/examples.html#fdpclust-py) in the docs.

What you see is expected as `a.subgraph(b)` adds (copies) the current content of `b` as a subgraph to `a`, i.e. it does **not** construct a compound object by adding a reference to `b` into `a`. Therefore the result of `b.subgraph(c)` in the next line only affects `b` and not `a`.

It works with the correct order:

```python
from graphviz import Graph

a = Graph(name='A')
a.edge('1', '2')

b = Graph(name='cluster_B')
b.edge('3', '4')

c = Graph(name='cluster_C')
c.edge('5', '6')

b.subgraph(c)
a.subgraph(b)

a
```

![A gv](https://user-images.githubusercontent.com/6342379/66635298-320eb500-ec0f-11e9-8c98-a5486a5fa4f9.png)

Note that when [using `.subgraph()` as a context-manager](https://graphviz.readthedocs.io/en/stable/manual.html#subgraphs-clusters), this kind of error cannot occur:

```python
 from graphviz import Graph

a = Graph(name='A')
a.edge('1', '2')

with a.subgraph(name='cluster_B') as b:
    b.edge('3', '4')

    with b.subgraph(name='cluster_C') as c:
        c.edge('5', '6')
```
