### ISSUE TITLE
Add xlabel to node

### ISSUE THREAD

**Issue by markthelaw** [xflr6/graphviz#85]
Curious if author plan add a 'xlabel' in addition to regular 'label' to the Node.

https://www.graphviz.org/doc/info/attrs.html#d:xlabel

**Comment by xflr6** [comment]
Hi, the [.node()-method](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Graph.node) passes arbitrary attributes given as kwargs, so I think this should be enough:
```python
g = graphviz.Graph()

g.node('spam', xlabel='eggs')

g
```

![spam](https://user-images.githubusercontent.com/6342379/66772077-2a276d00-eebc-11e9-9dc3-f862d5d1db62.png)

**Comment by markthelaw** [comment]
@xflr6 indeed thank you!!
