### ISSUE TITLE
cluster example renders, but gives errors in pylint

### ISSUE THREAD

**Issue by muteboy** [xflr6/graphviz#88]
"Instance of 'SubgraphContext' has no 'attr' member"
and so on

**Comment by xflr6** [comment]
Assuming you refer to this:

```shell
$ pylint examples/cluster.py
E: 12, 4: Instance of 'SubgraphContext' has no 'attr' member (no-member)
E: 13, 4: Instance of 'SubgraphContext' has no 'node_attr' member (no-member)
E: 14, 4: Instance of 'SubgraphContext' has no 'edges' member (no-member)
E: 15, 4: Instance of 'SubgraphContext' has no 'attr' member (no-member)
E: 18, 4: Instance of 'SubgraphContext' has no 'attr' member (no-member)
E: 19, 4: Instance of 'SubgraphContext' has no 'node_attr' member (no-member)
E: 20, 4: Instance of 'SubgraphContext' has no 'edges' member (no-member)
E: 21, 4: Instance of 'SubgraphContext' has no 'attr' member (no-member)
```
Seems to be a `pylint` bug (false positive) with context managers:

https://github.com/xflr6/graphviz/blob/7ef00d5bff8c56a5c787dd0e97853c8c5aa28334/graphviz/dot.py#L232-L233

Closing (see [pylint issues with context managers and no-member](https://github.com/PyCQA/pylint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++context+manager+no-member)).
