### ISSUE TITLE
there maybe some logical mistake in your package, when i try to make a feedback edge?

### ISSUE THREAD

**Issue by leslielee619** [xflr6/graphviz#93]
output is 'C25 [label=W5] ' but i want 'C25 -> W5'

all output is 
	Entry -> C3
	C3 -> W5
	W5 -> C6
	C6 -> W8
	W8 -> I9
	I9 -> C10
	I9 -> C14
	C10 -> W8
	C14 -> W8
	W8 -> I18
	C10 -> I18
	C14 -> I18
	I18 -> C19
	C19 -> F21
	F21 -> F22
	F22 -> F23
	F23 -> C25
	C25 [label=W5]
	I18 -> C25
	C25 -> W5
	C25 -> F27
	F27 -> F28
	F28 -> F29
	F29 -> End

**Comment by xflr6** [comment]
Hi. I am not sure I understand what this is about, can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by leslielee619** [comment]
maybe its my mistake which i dont find out. so please dont mind it. 
here is my small program:
------------------------------------
from graphviz import Digraph

g = Digraph('CFG')
node1 = g.node(name='Entry')
g.node(name='C3')
g.node(name='W5')
g.node(name='C6')
g.node(name='W8')
g.node(name='I9')
g.node(name='C10')
g.node(name='C14')
g.node(name='I18')
g.node(name='C19')
g.node(name='F21')
g.node(name='F22')
g.node(name='F23')
g.node(name='C25')
g.node(name='F27')
g.node(name='F28')
g.node(name='F29')
g.node(name='End')

g.edge('Entry', 'C3')
g.edge('C3', 'W5')
g.edge('W5', 'C6')
g.edge('C6', 'W8')
g.edge('W8', 'I9')
g.edge('I9', 'C10')
g.edge('I9', 'C14')
g.edge('C10', 'W8')
g.edge('C14', 'W8')
g.edge('W8', 'I18')
g.edge('C10', 'I18')
g.edge('C14', 'I18')

g.edge('I18', 'C19')
g.edge('C19', 'F21')
g.edge('F21', 'F22')
g.edge('F22', 'F23')
g.edge('F23', 'C25')
g.node('C25', 'W5')

g.edge('I18', 'C25')
g.edge('C25', 'W5')

g.edge('C25', 'F27')
g.edge('F27', 'F28')
g.edge('F28', 'F29')
g.edge('F29', 'End')

g.view(filename='test')
-----------------------------------
**********************************
------------------------------------
here is the output:
digraph CFG {
	Entry
	C3
	W5
	C6
	W8
	I9
	C10
	C14
	I18
	C19
	F21
	F22
	F23
	C25
	F27
	F28
	F29
	End
	Entry -> C3
	C3 -> W5
	W5 -> C6
	C6 -> W8
	W8 -> I9
	I9 -> C10
	I9 -> C14
	C10 -> W8
	C14 -> W8
	W8 -> I18
	C10 -> I18
	C14 -> I18
	I18 -> C19
	C19 -> F21
	F21 -> F22
	F22 -> F23
	F23 -> C25
	C25 [label=W5]
	I18 -> C25
	C25 -> W5
	C25 -> F27
	F27 -> F28
	F28 -> F29
	F29 -> End
}
--------------------------------
and i dont want  "C25 [label=W5]" ranther than "C25 ->W5"  .
i want the node C25 to flow to node W5, not to new build a label W5.
[test.pdf](https://github.com/xflr6/graphviz/files/4392543/test.pdf)

**Comment by leslielee619** [comment]
i want to use dot draw my c source code control flow graph. in my program, C means 'assignment', W means 'while', I means 'if', F means 'func call', and so on.

**Comment by xflr6** [comment]
I see. It seems you have an unintended `.node()` call:
```python
from graphviz import Digraph

g = Digraph('CFG')
node1 = g.node(name='Entry')

(...)

g.node('C25', 'W5')  # unintended?

g.edge('I18', 'C25')
g.edge('C25', 'W5')
```

**Comment by xflr6** [comment]
Commenting out that line gives this result (with the wanted C25 -> W5 'feedback edge' IIUC):

![graph](https://user-images.githubusercontent.com/6342379/77742950-97b4f900-7017-11ea-87a9-ff072d3740ab.png)

**Comment by leslielee619** [comment]
okay, i know it. thanks for your help.
