### ISSUE TITLE
graphviz's automatic layout causes the same graph to have a different layout each time it is drawn

### ISSUE THREAD

**Issue by ShadowLL** [xflr6/graphviz#94]
I found that graphviz's automatic layout causes the same graph to have a different layout each time. Is there a way to control its layout?

**Comment by xflr6** [comment]
Hi there. Different [engines](https://nbviewer.jupyter.org/github/xflr6/graphviz/blob/master/examples/graphviz-engines.ipynb) provide different kinds of options for controlling the layout (see [attrs.html](https://www.graphviz.org/doc/info/attrs.html)). This might be more of a question for [www.graphviz.org](https://www.graphviz.org/) ([master repo](https://gitlab.com/graphviz/graphviz/)): closing as this is for issues with this Python wrapper only.
