### ISSUE TITLE
Edge attr doens't working

### ISSUE THREAD

**Issue by jfpalomeque** [xflr6/graphviz#95]
Code ignoring instructions dot.attr('edge', splines="ortho")

**Comment by xflr6** [comment]
Hi. I am not sure I understand what this is about, can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by xflr6** [comment]
Maybe take a look at the "Used By" column in [attrs.html](https://www.graphviz.org/doc/info/attrs.html#h:uses): I suspect you might be mistaking `splines` for an `edge`-attr when it is in fact a `graph`-attr, e.g. the following:

```python
In [1]: import graphviz
   ...: 
   ...: g = graphviz.Graph()
   ...: 
   ...: g.attr('graph', splines='ortho')
   ...: g.edges(['AB', 'CB', 'CD'])
   ...: 
   ...: g
Out[1]: 
```
![graph](https://user-images.githubusercontent.com/6342379/78470171-89f22880-7727-11ea-9323-502d7fe84c04.png)

Closing for now.

**Comment by jfpalomeque** [comment]
Thanks a lot, was exactly that. And sorry because my question was done in a really awful way.

**Comment by xflr6** [comment]
Thanks for the confirmation, happy to help.
