### ISSUE TITLE
enhance doc by adding links to sourcecode

### ISSUE THREAD

**Issue by sappelhoff** [xflr6/graphviz#97]
When browsing the docs, advanced users may want to directly jump to the sourcecode.

This is easily possible with this sphinx extension: https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html

It creates a `[source]` link as in this image (lower right): 

![image](https://user-images.githubusercontent.com/9084751/79747136-79d36f00-830b-11ea-9fdb-7cb642efd3cf.png)

([try it  out here](https://mne.tools/mne-bids/stable/generated/mne_bids.write_raw_bids.html#mne_bids.write_raw_bids))

we'd only need to add a line here:

https://github.com/xflr6/graphviz/blob/c2246c90cae8da69803d5ae22b6c8e116f665d88/docs/conf.py#L42-L47

**Comment by xflr6** [comment]
Thanks. I think I have tried it before and I would mildly prefer a link to the repository (which [sphinx.ext.linkcode](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) can in principle do but then again I think it cannot link to the exact lines and selecting the correct version for `latest` vs. `stable` might be tricky).

Try the [latest doc build](https://graphviz.readthedocs.io/en/latest/api.html), I am not sure if it makes much sense as it does not seem to combine with inheritance, so you still need to go to the repo or the source files to see what's going on, WDYT?

**Comment by sappelhoff** [comment]
You are right, it's not as helpful as it could be, and one would still have to go to the sourcecode ... but I think it's an improvement and it can provide first hints where to look at. :-)

**Comment by xflr6** [comment]
Allright, lets's leave it on then. Closing.

**Comment by sappelhoff** [comment]
Thanks for the quick action @xflr6

**Comment by xflr6** [comment]
Thanks for the suggestion :)
