### ISSUE TITLE
test_backend.py failures: "TypeError: tuple indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by PureTryOut** [xflr6/graphviz#99]
Several tests in `tests/test_backend.py` are failing for me:

```
>       check_startupinfo(Popen.call_args.kwargs['startupinfo'])
E       TypeError: tuple indices must be integers or slices, not str
```

This is on Python 3.8 on Alpine Linux with the latest versions of all dependencies.

**Comment by xflr6** [comment]
Thanks. Please provide the steps to reproduce this and/or more `pytest` output (e.g. version).

Did you install the [`test` extra](https://github.com/xflr6/graphviz/blob/c24ac2020c2d26c2f54972dd9e53f4779944561b/tox.ini#L6) dependency (e.g. `pip install -e .[test]`)?

https://github.com/xflr6/graphviz/blob/c24ac2020c2d26c2f54972dd9e53f4779944561b/setup.py#L25

The `kwargs` property on `mock.call()` objects which is used here was [added in `mock` 3.0](https://github.com/testing-cabal/mock/blob/master/CHANGELOG.rst#300)

**Comment by PureTryOut** [comment]
Ah, our `mock` is hopelessly out of date, that makes sense. Sorry for bothering you, thanks for your answer!

**Comment by xflr6** [comment]
No worries, thanks for the update.
